#!/usr/bin/env python3
"""
WM 2026 – Teams & Kader CSV-Export
Quelle: Offizielles FIFA-PDF (21.06.2026) + Wikipedia für nicht im PDF enthaltene Teams
"""
import csv, json, os, re

OUT = os.path.dirname(os.path.abspath(__file__))

# ── Verein → Land-Code ────────────────────────────────────────────────────────
CLUB_LAND = {
    '1. FC Union Berlin':'GER','1. FSV Mainz 05':'GER','Bayer 04 Leverkusen':'GER',
    'Bayern Munich':'GER','Borussia Dortmund':'GER','Borussia Mönchengladbach':'GER',
    'Eintracht Frankfurt':'GER','FC Augsburg':'GER','FC Bayern München':'GER',
    'FC Cosmos Koblenz':'GER','FC Schalke 04':'GER','Fortuna Düsseldorf':'GER',
    'Hamburger SV':'GER','Hannover 96':'GER','Holstein Kiel':'GER',
    'Jahn Regensburg':'GER','Karlsruher SC':'GER','Mainz 05':'GER','Meippen':'GER',
    'RB Leipzig':'GER','SC Freiburg':'GER','TSG Hoffenheim':'GER','VfB Stuttgart':'GER',
    'VfL Wolfsburg':'GER','SV Werder Bremen':'GER','FC St. Pauli':'GER',
    'AFC Bournemouth':'ENG','Arsenal FC':'ENG','Aston Villa FC':'ENG','Barnsley':'ENG',
    'Brentford FC':'ENG','Brighton & Hove Albion FC':'ENG','Burnley':'ENG','Burnley FC':'ENG',
    'Charlton Athletic':'ENG','Chelsea FC':'ENG','Coventry City':'ENG','Coventry City FC':'ENG',
    'Crystal Palace FC':'ENG','Derby County':'ENG','Everton FC':'ENG','Fulham':'ENG',
    'Fulham FC':'ENG','Hull City FC':'ENG','Ipswich Town':'ENG','Leeds United':'ENG',
    'Leicester City FC':'ENG','Liverpool FC':'ENG','Manchester City FC':'ENG',
    'Manchester United FC':'ENG','Middlesbrough FC':'ENG','Millwall':'ENG',
    'Newcastle United FC':'ENG','Norwich City FC':'ENG','Nottingham Forest':'ENG',
    'Nottingham Forest FC':'ENG','Portsmouth FC':'ENG','Rotherham United FC':'ENG',
    'Sheffield United FC':'ENG','Southampton FC':'ENG','Stoke City':'ENG',
    'Sunderland':'ENG','Sunderland AFC':'ENG','Swansea City':'ENG','Swansea City AFC':'ENG',
    'Tottenham Hotspur FC':'ENG','Watford FC':'ENG','West Ham United FC':'ENG',
    'Wolverhampton Wanderers':'ENG','Wolverhampton Wanderers FC':'ENG',
    'Wrexham':'WAL','Birmingham City':'ENG',
    'AJ Auxerre':'FRA','AS Monaco':'FRA','AS Nancy':'FRA','AS Saint-Etienne':'FRA',
    'FC Lorient':'FRA','FC Nantes':'FRA','Le Havre AC':'FRA','Lille OSC':'FRA',
    'Lorient':'FRA','Montpellier HSC':'FRA','OGC Nice':'FRA','Olympique Lyonnais':'FRA',
    'Olympique Marseille':'FRA','Paris FC':'FRA','Paris Saint-Germain':'FRA',
    'RC Lens':'FRA','RC Strasbourg':'FRA','Rennes':'FRA','SC Bastia':'FRA',
    'Stade Rennais FC':'FRA','Stade de Reims':'FRA','Strasbourg':'FRA','Toulouse FC':'FRA',
    'Athletic Club':'ESP','Atlético de Madrid':'ESP','CA Osasuna':'ESP',
    'CD Castellón':'ESP','CD Guadalajara':'ESP','Cultural Leonesa':'ESP',
    'Deportivo Alavés':'ESP','Elche CF':'ESP','FC Barcelona':'ESP','Girona FC':'ESP',
    'Granada CF':'ESP','Racing Santander':'ESP','RCD Espanyol':'ESP','RCD Mallorca':'ESP',
    'RC Celta de Vigo':'ESP','Rayo Vallecano':'ESP','Real Betis':'ESP',
    'Real Madrid C.F.':'ESP','Real Oviedo':'ESP','Real Sociedad':'ESP','Sevilla FC':'ESP',
    'Almería':'ESP','Valencia CF':'ESP','Villarreal CF':'ESP','Levante UD':'ESP',
    'AC Milan':'ITA','AC Pisa':'ITA','ACF Fiorentina':'ITA','Atalanta Bergamo':'ITA',
    'Bologna FC':'ITA','Cagliari':'ITA','Cagliari Calcio':'ITA','Como':'ITA',
    'Cremonese':'ITA','Empoli FC':'ITA','FC Internazionale Milano':'ITA','Frosinone':'ITA',
    'Genoa':'ITA','Hellas Verona FC':'ITA','Juventus FC':'ITA','Lecce':'ITA',
    'Parma':'ITA','AS Roma':'ITA','SS Lazio':'ITA','SSC Napoli':'ITA','Torino FC':'ITA',
    'UC Sampdoria':'ITA','US Sassuolo':'ITA','Sassuolo':'ITA','Udinese Calcio':'ITA','Venezia FC':'ITA',
    'AFC Ajax':'NED','AZ':'NED','FC Den Bosch':'NED','FC Emmen':'NED','FC Twente':'NED',
    'FC Volendam':'NED','Feyenoord':'NED','Feyenoord Rotterdam':'NED',
    'Go Ahead Eagles':'NED','NEC Nijmegen':'NED','PEC Zwolle':'NED','PSV Eindhoven':'NED',
    'RKC Waalwijk':'NED','Roda JC Kerkrade':'NED','SC Heracles Almelo':'NED',
    'SC Telstar':'NED','Sparta Rotterdam':'NED','VVV Venlo':'NED','Vitesse':'NED','Almere City FC':'NED',
    'CF Estrela da Amadora':'POR','FC Porto':'POR','GD Chaves':'POR','SC Braga':'POR',
    'SC Farense':'POR','SL Benfica':'POR','SCU Torreense':'POR','Sporting CP':'POR',
    'Vitória SC':'POR','FC Vizela':'POR','Casa Pia AC':'POR','Gil Vicente FC':'POR',
    'Anderlecht':'BEL','Cercle Brugge':'BEL','Club Brugge':'BEL','FCV Dender EH':'BEL',
    'KAA Gent':'BEL','KRC Genk':'BEL','KV Kortrijk':'BEL','KV Oostende':'BEL',
    'Mechelen':'BEL','Royal Antwerp FC':'BEL','Royale Union Saint-Gilloise':'BEL',
    'RSC Anderlecht':'BEL','SK Beveren':'BEL','Sporting Charleroi':'BEL',
    'SV Zulte Waregem':'BEL','Standard Liège':'BEL',
    'BSC Young Boys':'SUI','FC Lugano':'SUI','FC St. Gallen':'SUI',
    'FC Stade Nyonnais':'SUI','FC Zürich':'SUI','FC Zurich':'SUI','Servette FC':'SUI',
    'Austria Wien':'AUT','FC Red Bull Salzburg':'AUT','Grazer AK':'AUT',
    'LASK Linz':'AUT','Red Bull Salzburg':'AUT','SK Sturm Graz':'AUT','Wolfsberger AC':'AUT','Rapid Wien':'AUT',
    'Celtic':'SCO','Celtic FC':'SCO','Heart Of Midlothian FC':'SCO',
    'Heart of Midlothian':'SCO','Hibernian':'SCO','Kilmarnock FC':'SCO','Rangers FC':'SCO','Livingston FC':'SCO',
    'Alanyaspor':'TUR','Başakşehir FK':'TUR','Besiktas JK':'TUR','Beşiktaş':'TUR',
    'Beşiktaş JK':'TUR','Fenerbahçe':'TUR','Fenerbahçe SK':'TUR','Galatasaray SK':'TUR',
    'Gaziantep FK':'TUR','Iğdır FK':'TUR','Kasımpaşa':'TUR','Kayserispor':'TUR',
    'Konyaspor':'TUR','Trabzonspor':'TUR','Çaykur Rizespor':'TUR',
    'Dynamo Makhachkala':'RUS','Dynamo Moscow':'RUS','FC Akron Tolyatti':'RUS',
    'FC Krasnodar':'RUS','FC Spartak Moscow':'RUS','FC Zenit St. Petersburg':'RUS','Lokomotiv Moscow':'RUS',
    'AEK Athens':'GRE','AE Kifisia FC':'GRE','Atromitos FC':'GRE','Olympiacos FC':'GRE',
    'Panathinaikos FC':'GRE','PAOK':'GRE','PAOK Saloniki':'GRE',
    'AC Omonia':'CYP','AEL FC':'CYP','AEL Limassol':'CYP','Anorthosis Famagusta':'CYP',
    'Apollon Limassol':'CYP','Aris Limassol FC':'CYP','Pafos FC':'CYP','APOEL FC':'CYP',
    'Brøndby IF':'DEN','FC Copenhagen':'DEN','FC København':'DEN','FC Midtjylland':'DEN',
    'FC Nordsjælland':'DEN','Midtjylland':'DEN','Randers FC':'DEN',
    'AIK':'SWE','Djurgårdens IF':'SWE','IFK Göteborg':'SWE','IFK Norrköping':'SWE','Malmö FF':'SWE','Mjällby AIF':'SWE',
    'Bodo/Glimt':'NOR','Molde':'NOR','Start':'NOR',
    'SJK':'FIN',
    'Jagiellonia Białystok':'POL','Widzew Łódź':'POL','Górnik Zabrze':'POL',
    'AC Sparta Praha':'CZE','FC Hradec Králové':'CZE','FC Slovan Liberec':'CZE','FC Viktoria Plzeň':'CZE','SK Slavia Praha':'CZE',
    'FC Tatran Prešov':'SVK',
    'Ferencvárosi TC':'HUN','Györi ETO FC':'HUN','Puskás Akadémia FC':'HUN',
    'FC FCSB':'ROU','Universitatea Cluj':'ROU',
    'FK Crvena Zvezda':'SRB','Red Star Belgrade':'SRB',
    'GNK Dinamo Zagreb':'CRO','HNK Hajduk Split':'CRO','HNK Rijeka':'CRO',
    'FK Borac Banja Luka':'BIH',
    'NK Maribor':'SVN',
    'PFC Ludogorets Razgrad':'BUL','PFC Montana':'BUL',
    'Hapoel Haifa':'ISR','Maccabi Haifa FC':'ISR','Maccabi Tel-Aviv FC':'ISR',
    'Shamrock Rovers FC':'IRL',"St Patrick's Athletic FC":'IRL',
    'FC Noah':'ARM',
    'FC Astana':'KAZ',
    'FK AGMK':'UZB','FK Metallurg':'UZB','Lokomotiv Tashkent':'UZB','Nasaf':'UZB','Navbahor':'UZB','Pakhtakor':'UZB',
    'Qarabag FK':'AZE',
    'Abha Club':'KSA','Al Ahli FC':'KSA','Al Hilal SC':'KSA','Al Ittihad':'KSA',
    'Al Qadsiah FC':'KSA','Al Qadsiah':'KSA','Al-Ahli':'KSA','Al-Ettifaq':'KSA',
    'Al-Fateh':'KSA','Al-Fayha':'KSA','Al-Hilal':'KSA','Al-Ittihad':'KSA',
    'Al-Nassr':'KSA','Al-Qadsiah':'KSA','Al-Shabab':'KSA',
    'Al Duhail SC':'QAT','Al Wakrah SC':'QAT','Al-Arabi':'QAT','Al-Duhail':'QAT',
    'Al-Gharafa':'QAT','Al-Rayyan':'QAT','Al-Sadd':'QAT','Al-Shamal':'QAT','Al-Wakrah':'QAT',
    'Al Ain FC':'UAE','Al Jazira':'UAE','Al Bataeh Club':'UAE','Al-Ain':'UAE','Al-Wahda':'UAE','Al-Qasimy':'UAE',
    'Al-Faisaly':'JOR','Al-Jazeera':'JOR','Al-Ramtha':'JOR','Al-Sareeh':'JOR','Al-Wehdat':'JOR',
    'Al-Riffa':'BHR','Al Najmah SC':'BHR',
    'Al-Shorta':'IRQ','Al-Zawraa':'IRQ',
    'Al Ahly':'EGY','Al Ahly FC':'EGY','El Gouna FC':'EGY','Pyramids FC':'EGY','Zamalek SC':'EGY','ZED FC':'EGY',
    'AS FAR':'MAR','RS Berkane':'MAR',
    'Club Africain':'TUN','CS Sfaxien':'TUN','Espérance de Tunis':'TUN',
    'Espérance de Tunisie':'TUN','US Monastir':'TUN','Étoile du Sahel':'TUN',
    'JS Kabylie':'ALG','USM Alger':'ALG',
    'Hearts of Oak SC':'GHA',
    'Kaizer Chiefs':'RSA','Mamelodi Sundowns':'RSA','Orlando Pirates':'RSA','Polokwane City':'RSA','Siwelele':'RSA',
    'Esteghlal FC':'IRN','Esteghlal Tehran FC':'IRN','Persepolis FC':'IRN',
    'Perspolis FC':'IRN','Sepahan SC':'IRN','Tractor SC':'IRN','Teheran':'IRN',
    'Athletico Paranaense':'BRA','Atlético Mineiro':'BRA','Botafogo':'BRA',
    'CR Flamengo':'BRA','CR Vasco da Gama':'BRA','Grêmio FBPA':'BRA',
    'Red Bull Bragantino':'BRA','SC Corinthians Paulista':'BRA','SC Internacional':'BRA',
    'SE Palmeiras':'BRA','Santos FC':'BRA','São Paulo FC':'BRA',
    'CA Boca Juniors':'ARG','CA Huracán':'ARG','CA Independiente':'ARG',
    'CA River Plate':'ARG','CA Rosario Central':'ARG','CA Vélez Sarsfield':'ARG',
    'Club Atlético Independiente':'ARG','Independiente':'ARG','Independiente Rivadavia':'ARG',
    'Lanús':'ARG','San Lorenzo':'ARG','Talleres':'ARG',
    'Atlético Nacional':'COL',
    'Independiente del Valle':'ECU','LDU Quito':'ECU',
    'CD Nacional':'PAR','CD Olimpia':'PAR','Cerro Porteño':'PAR',
    'Montevideo City Torque':'URU',
    'Arabe Unido':'PAN','CD Plaza Amador':'PAN',
    'CD Victoria':'HON','CD Saprissa':'CRC','Deportivo Saprissa':'CRC','Deportivo Independiente':'CRC',
    'América':'MEX','Atlas FC':'MEX','CF Cruz Azul':'MEX','CF Pachuca':'MEX',
    'Club Tijuana':'MEX','Cruz Azul':'MEX','Guadalajara':'MEX','Pumas UNAM':'MEX',
    'Santos Laguna':'MEX','Tijuana':'MEX','Toluca':'MEX','UNAM':'MEX',
    'Atlanta United FC':'USA','Charlotte FC':'USA','Chicago Fire FC':'USA',
    'Colorado Rapids':'USA','Colorado Springs Switchbacks FC':'USA','Columbus Crew':'USA',
    'El Paso Locomotive FC':'USA','FC Cincinnati':'USA','FC Dallas':'USA',
    'Inter Miami CF':'USA','Los Angeles FC':'USA','Miami FC':'USA',
    'Minnesota United FC':'USA','Nashville SC':'USA','New England Revolution':'USA',
    'New York City FC':'USA','New York Red Bulls':'USA','Orlando City SC':'USA',
    'Philadelphia Union':'USA','San Diego FC':'USA','Seattle Sounders FC':'USA','Sporting Kansas City':'USA',
    'CF Montréal':'CAN','Toronto FC':'CAN','Vancouver Whitecaps FC':'CAN',
    'Brisbane Roar':'AUS','Melbourne City FC':'AUS','Melbourne Victory FC':'AUS','Sydney FC':'AUS',
    'Auckland FC':'NZL',
    'Albirex Niigata':'JPN','FC Machida Zelvia':'JPN','FC Tokyo':'JPN','Kashima Antlers':'JPN','Sanfrecce Hiroshima':'JPN',
    'Daejeon Hana Citizen':'KOR','Gangwon FC':'KOR','Jeonbuk Hyundai Motors':'KOR','Ulsan HD':'KOR',
    'Buriram United':'THA','Terengganu FC':'MAS','Zhejiang':'CHN',
}


# ── Gruppen ──────────────────────────────────────────────────────────────────
GRUPPEN = [
    ('A', ['Mexiko','Südafrika','Südkorea','Tschechien']),
    ('B', ['Kanada','Bosnien-Herzegowina','Katar','Schweiz']),
    ('C', ['Brasilien','Marokko','Haiti','Schottland']),
    ('D', ['USA','Paraguay','Australien','Türkei']),
    ('E', ['Deutschland','Curaçao','Elfenbeinküste','Ecuador']),
    ('F', ['Niederlande','Japan','Schweden','Tunesien']),
    ('G', ['Belgien','Ägypten','Iran','Neuseeland']),
    ('H', ['Spanien','Kap Verde','Saudi-Arabien','Uruguay']),
    ('I', ['Frankreich','Senegal','Irak','Norwegen']),
    ('J', ['Argentinien','Algerien','Österreich','Jordanien']),
    ('K', ['Portugal','Kongo DR','Usbekistan','Kolumbien']),
    ('L', ['England','Kroatien','Panama','Ghana']),
]

# ── Kaderdaten ────────────────────────────────────────────────────────────────
# Format: [pos, name, jg, club, caps]
# Quellen: FIFA-PDF Seite 1-22 (21.06.2026), Wikipedia für übrige Teams
# (ca.) = Schätzung aus Trainingsdaten

KADER = {

'Algerien': [
    ['GK','Melvin Mastil',2000,'FC Stade Nyonnais',2],
    ['DF','Aissa Mandi',1991,'Lille OSC',120],
    ['DF','Achref Abada',1999,'USM Alger',10],
    ['DF','Mohamed Amine Tougai',2000,'Espérance de Tunisie',30],
    ['DF','Zineddine Belaïd',1999,'JS Kabylie',18],
    ['MF','Ramiz Zerrouki',1998,'FC Twente',54],
    ['FW','Riyad Mahrez',1991,'Al Ahli FC',117],
    ['MF','Houssem Aouar',1998,'Al Ittihad',24],
    ['FW','Amine Gouiri',2000,'Olympique Marseille',24],
    ['MF','Fares Chaibi',2002,'Eintracht Frankfurt',32],
    ['FW','Anis Hadj Moussa',2002,'Feyenoord Rotterdam',16],
    ['FW','Nadhir Benbouali',2000,'Györi ETO FC',4],
    ['DF','Jaouen Hadjam',2003,'BSC Young Boys',18],
    ['MF','Hicham Boudaoui',1999,'OGC Nice',35],
    ['DF','Rayan Aït-Nouri',2001,'Manchester City FC',31],
    ['GK','Oussama Benbot',1994,'USM Alger',3],
    ['DF','Rak Belghali',2002,'Hellas Verona FC',14],
    ['FW','Mohammed Amoura',2000,'VfL Wolfsburg',48],
    ['MF','Nabil Bentaleb',1994,'Lille OSC',61],
    ['FW','Adil Boulbina',2003,'Al Duhail SC',12],
    ['DF','Ramy Bensebaini',1995,'Borussia Dortmund',83],
    ['MF','Ibrahim Maza',2005,'Bayer 04 Leverkusen',18],
    ['GK','Luca Zidane',1998,'Granada CF',8],
    ['MF','Yassine Titraoui',2003,'Sporting Charleroi',5],
    ['FW','Fares Ghedjemis',2002,'Frosinone',1],
    ['DF','Samir Chergui',1999,'Paris FC',5],
],

'Argentinien': [
    ['GK','Juan Musso',1994,'Atlético de Madrid',4],
    ['DF','Marcos Senesi',1997,'AFC Bournemouth',3],
    ['DF','Nicolás Tagliafico',1992,'Olympique Lyonnais',76],
    ['DF','Gonzalo Montiel',1997,'CA River Plate',40],
    ['MF','Leandro Paredes',1994,'CA Boca Juniors',77],
    ['DF','Lisandro Martínez',1998,'Manchester United FC',29],
    ['MF','Rodrigo De Paul',1994,'Inter Miami CF',88],
    ['MF','Valentin Barco',2004,'RC Strasbourg',4],
    ['FW','Julián Álvarez',2000,'Atlético de Madrid',52],
    ['FW','Lionel Messi',1987,'Inter Miami CF',200],
    ['MF','Giovani Lo Celso',1996,'Real Betis',67],
    ['GK','Gerónimo Rulli',1992,'Olympique Marseille',8],
    ['DF','Cristian Romero',1998,'Tottenham Hotspur FC',52],
    ['MF','Exequiel Palacios',1998,'Bayer 04 Leverkusen',40],
    ['MF','Nicolás González',1998,'Atlético de Madrid',52],
    ['FW','Thiago Almada',2001,'Atlético de Madrid',17],
    ['FW','Giuliano Simeone',2002,'Atlético de Madrid',13],
    ['FW','Nico Paz',2004,'Como',10],
    ['DF','Nicolás Otamendi',1988,'SL Benfica',133],
    ['MF','Alexis Mac Allister',1998,'Liverpool FC',47],
    ['FW','José Lopez',2000,'SE Palmeiras',5],
    ['FW','Lautaro Martínez',1997,'FC Internazionale Milano',78],
    ['GK','Emiliano Martínez',1992,'Aston Villa FC',60],
    ['MF','Enzo Fernández',2001,'Chelsea FC',43],
    ['DF','Facundo Medina',1999,'Olympique Marseille',10],
    ['DF','Nahuel Molina',1998,'Atlético de Madrid',59],
],

'Australien': [
    ['GK','Mathew Ryan',1992,'Levante UD',104],
    ['DF','Miloš Degenek',1994,'APOEL FC',57],
    ['DF','Alessandro Circati',2003,'Parma',15],
    ['DF','Jacob Italiano',2001,'Grazer AK',7],
    ['DF','Jordan Bos',2002,'Feyenoord Rotterdam',29],
    ['DF','Jason Geria',1993,'Albirex Niigata',16],
    ['FW','Mathew Leckie',1991,'Melbourne City FC',82],
    ['MF','Connor Metcalfe',1999,'FC St. Pauli',38],
    ['FW','Mohamed Touré',2004,'Norwich City FC',12],
    ['MF','Ajdin Hrustic',1996,'SC Heracles Almelo',37],
    ['FW','Awer Mabil',1995,'CD Castellón',38],
    ['GK','Paul Izzo',1995,'Randers FC',4],
    ['MF','Aiden O\'Neill',1998,'New York City FC',33],
    ['MF','Cameron Devlin',1998,'Heart Of Midlothian FC',5],
    ['DF','Kai Trewin',2001,'New York City FC',6],
    ['DF','Aziz Behich',1990,'Melbourne City FC',85],
    ['FW','Nestory Irankunda',2006,'Watford FC',17],
    ['GK','Patrick Beach',2003,'Melbourne City FC',4],
    ['DF','Harry Souttar',1998,'Leicester City FC',40],
    ['FW','Cristian Volpato',2003,'US Sassuolo',2],
    ['DF','Cameron Burgess',1995,'Swansea City AFC',29],
    ['MF','Jackson Irvine',1993,'FC St. Pauli',84],
    ['FW','Nishan Velupillay',2001,'Melbourne Victory FC',9],
    ['MF','Paul Okon-Engstler',2005,'Sydney FC',8],
    ['DF','Lucas Herrington',2007,'Colorado Rapids',4],
    ['FW','Tete Yengi',2000,'FC Machida Zelvia',2],
],

'Österreich': [
    ['GK','Alexander Schlager',1996,'FC Red Bull Salzburg',27],
    ['DF','David Affengruber',2001,'Elche CF',1],
    ['DF','Kevin Danso',1998,'Tottenham Hotspur FC',33],
    ['MF','Xaver Schlager',1997,'RB Leipzig',52],
    ['DF','Stefan Posch',1997,'1. FSV Mainz 05',53],
    ['MF','Nicolas Seiwald',2001,'RB Leipzig',48],
    ['FW','Marko Arnautovic',1989,'FK Crvena Zvezda',134],
    ['DF','David Alaba',1992,'Real Madrid C.F.',114],
    ['MF','Marcel Sabitzer',1994,'Borussia Dortmund',99],
    ['MF','Florian Grillitsch',1995,'SC Braga',59],
    ['FW','Michael Gregoritsch',1994,'FC Augsburg',75],
    ['GK','Florian Wiegele',2001,'FC Viktoria Plzeň',1],
    ['GK','Patrick Pentz',1997,'Brøndby IF',18],
    ['FW','Saša Kalajdžić',1997,'LASK Linz',23],
    ['DF','Philipp Lienhart',1996,'SC Freiburg',42],
    ['DF','Phillip Mwene',1994,'1. FSV Mainz 05',31],
    ['MF','Carney Chukwuemeka',2003,'Borussia Dortmund',4],
    ['MF','Romano Schmid',2000,'SV Werder Bremen',35],
    ['MF','Dejan Ljubičić',1997,'FC Schalke 04',9],
    ['MF','Konrad Laimer',1997,'FC Bayern München',58],
    ['FW','Patrick Wimmer',2001,'VfL Wolfsburg',31],
    ['MF','Alexander Prass',2001,'TSG Hoffenheim',19],
    ['DF','Marco Friedl',1998,'SV Werder Bremen',11],
    ['MF','Paul Wanner',2005,'PSV Eindhoven',4],
    ['DF','Michael Svoboda',1998,'Venezia FC',4],
    ['MF','Alessandro Schöpf',1994,'Wolfsberger AC',35],
],

'Belgien': [
    ['GK','Thibaut Courtois',1992,'Real Madrid C.F.',110],
    ['DF','Zeno Debast',2003,'Sporting CP',26],
    ['DF','Arthur Theate',2000,'Eintracht Frankfurt',33],
    ['DF','Brandon Mechele',1993,'Club Brugge',10],
    ['DF','Maxim De Cuyper',2000,'Brighton & Hove Albion FC',20],
    ['MF','Axel Witsel',1989,'Girona FC',138],
    ['MF','Kevin De Bruyne',1991,'SSC Napoli',120],
    ['MF','Youri Tielemans',1997,'Aston Villa FC',86],
    ['FW','Romelu Lukaku',1993,'SSC Napoli',127],
    ['FW','Leandro Trossard',1994,'Arsenal FC',52],
    ['FW','Jeremy Doku',2002,'Manchester City FC',44],
    ['GK','Senne Lammens',2002,'Manchester United FC',2],
    ['GK','Mike Penders',2005,'RC Strasbourg',0],
    ['FW','Dodi Lukebakio',1997,'SL Benfica',30],
    ['DF','Thomas Meunier',1991,'Lille OSC',81],
    ['DF','Koni De Winter',2002,'AC Milan',8],
    ['FW','Charles De Ketelaere',2001,'Atalanta Bergamo',31],
    ['DF','Joaquin Seys',2005,'Club Brugge',5],
    ['MF','Diego Moreira',2004,'RC Strasbourg',3],
    ['MF','Hans Vanaken',1992,'Club Brugge',35],
    ['DF','Timothy Castagne',1995,'Fulham FC',64],
    ['MF','Alexis Saelemaekers',1999,'AC Milan',24],
    ['MF','Nicolas Raskin',2001,'Rangers FC',14],
    ['MF','Amadou Onana',2001,'Aston Villa FC',30],
    ['DF','Nathan Ngoy',2003,'Lille OSC',5],
    ['FW','Matias Fernandez-Pardo',2005,'Lille OSC',3],
],

'Bosnien-Herzegowina': [
    ['GK','Nikola Vasilj',1995,'FC St. Pauli',28],
    ['DF','Nihad Mujakić',1998,'Gaziantep FK',12],
    ['DF','Dennis Hadžikadunić',1998,'UC Sampdoria',32],
    ['DF','Tarik Muharemović',2003,'US Sassuolo',16],
    ['DF','Sead Kolašinac',1993,'Atalanta Bergamo',67],
    ['MF','Benjamin Tahirović',2003,'Brøndby IF',30],
    ['DF','Amar Dedić',2002,'SL Benfica',30],
    ['MF','Armin Gigović',2002,'BSC Young Boys',21],
    ['FW','Samed Baždar',2004,'Jagiellonia Białystok',14],
    ['FW','Ermedin Demirović',1998,'VfB Stuttgart',42],
    ['FW','Edin Džeko',1986,'FC Schalke 04',149],
    ['GK','Mladen Jurkas',2007,'FK Borac Banja Luka',0],
    ['MF','Ivan Bašić',2002,'FC Astana',19],
    ['MF','Ivan Šunjić',1996,'Pafos FC',13],
    ['MF','Amar Memić',2001,'FC Viktoria Plzeň',15],
    ['MF','Amir Hadžiahmetović',1997,'Hull City FC',37],
    ['MF','Dženis Burnić',1998,'Karlsruher SC',21],
    ['DF','Nikola Katić',1996,'FC Schalke 04',19],
    ['FW','Kerim Alajbegović',2007,'FC Red Bull Salzburg',12],
    ['MF','Esmir Bajraktarević',2005,'PSV Eindhoven',18],
    ['DF','Stjepan Radeljić',1997,'HNK Rijeka',5],
    ['GK','Martin Zlomislić',1998,'HNK Rijeka',3],
    ['FW','Haris Tabaković',1994,'Borussia Mönchengladbach',10],
    ['DF','Arjan Malić',2005,'SK Sturm Graz',8],
    ['FW','Jovo Lukić',1998,'Universitatea Cluj',5],
    ['MF','Ermin Mahmić',2005,'FC Slovan Liberec',3],
],

'Brasilien': [
    ['GK','Alisson',1992,'Liverpool FC',80],
    ['MF','Éderson Silva',1999,'Atalanta Bergamo',4],
    ['DF','Gabriel Magalhães',1997,'Arsenal FC',19],
    ['DF','Marquinhos',1994,'Paris Saint-Germain',107],
    ['MF','Casemiro',1992,'Manchester United FC',88],
    ['DF','Alex Sandro',1991,'CR Flamengo',45],
    ['FW','Vinícius Júnior',2000,'Real Madrid C.F.',51],
    ['MF','Bruno Guimarães',1997,'Newcastle United FC',45],
    ['FW','Matheus Cunha',1999,'Manchester United FC',25],
    ['FW','Neymar',1992,'Santos FC',128],
    ['FW','Raphinha',1996,'FC Barcelona',41],
    ['GK','Weverton',1987,'Grêmio FBPA',11],
    ['DF','Danilo Luiz',1991,'CR Flamengo',72],
    ['DF','Bremer',1997,'Juventus FC',8],
    ['DF','Léo Pereira',1996,'CR Flamengo',4],
    ['DF','Douglas Santos',1994,'FC Zenit St. Petersburg',9],
    ['MF','Fabinho',1993,'Al Ittihad',34],
    ['MF','Danilo Santos',2001,'Botafogo',6],
    ['FW','Endrick',2006,'Olympique Lyonnais',18],
    ['MF','Lucas Paquetá',1997,'CR Flamengo',65],
    ['FW','Luiz Henrique',2001,'FC Zenit St. Petersburg',16],
    ['FW','Gabriel Martinelli',2001,'Arsenal FC',24],
    ['GK','Ederson',1993,'Fenerbahçe SK',32],
    ['DF','Roger Ibañez',1998,'Al Ahli FC',8],
    ['FW','Igor Thiago',2001,'Brentford FC',5],
    ['FW','Rayan',2006,'AFC Bournemouth',3],
],

'Kap Verde': [
    ['GK','Vozinha',1986,'GD Chaves',91],
    ['DF','Stopira',1988,'SCU Torreense',61],
    ['DF','Diney Borges',1995,'Al Bataeh Club',33],
    ['DF','Pico Lopes',1992,'Shamrock Rovers FC',46],
    ['DF','Logan Costa',2001,'Villarreal CF',28],
    ['MF','Kevin Pina',1997,'FC Krasnodar',32],
    ['MF','Jovane Cabral',1998,'CF Estrela da Amadora',30],
    ['MF','João Paulo',1998,'FC FCSB',42],
    ['FW','Gilson Benchimol',2001,'FC Akron Tolyatti',21],
    ['MF','Jamiro Monteiro',1993,'PEC Zwolle',56],
    ['MF','Garry Rodrigues',1990,'Apollon Limassol',61],
    ['GK','Márcio Rosa',1997,'PFC Montana',11],
    ['DF','Sidny Lopes Cabral',2002,'SL Benfica',12],
    ['MF','Deroy Duarte',1999,'PFC Ludogorets Razgrad',34],
    ['MF','Laros Duarte',1997,'Puskás Akadémia FC',21],
    ['MF','Yannick Semedo',1995,'SC Farense',11],
    ['MF','Willy Semedo',1994,'AC Omonia',39],
    ['MF','Telmo Arcanjo',2001,'Vitória SC',17],
    ['FW','Dailon Livramento',2001,'Casa Pia AC',23],
    ['FW','Ryan Mendes',1990,'Iğdır FK',99],
    ['MF','Nuno Da Costa',1991,'Başakşehir FK',10],
    ['DF','Steven Moreira',1994,'Columbus Crew',21],
    ['GK','CJ Dos Santos',2000,'San Diego FC',1],
    ['DF','Wagner Pina',2002,'Trabzonspor',14],
    ['DF','Kelvin Pires',2000,'SJK',6],
    ['MF','Hélio Varela',2002,'Maccabi Tel-Aviv FC',21],
],

'Kanada': [
    ['GK','Dayne St. Clair',1997,'Inter Miami CF',20],
    ['DF','Alistair Johnston',1998,'Celtic FC',60],
    ['DF','Alfie Jones',1997,'Middlesbrough FC',2],
    ['DF','Luc De Fougerolles',2005,'FCV Dender EH',15],
    ['DF','Joel Waterman',1996,'Chicago Fire FC',17],
    ['MF','Mathieu Choinière',1999,'Los Angeles FC',24],
    ['MF','Stephen Eustáquio',1996,'Los Angeles FC',58],
    ['MF','Ismaël Koné',2002,'US Sassuolo',42],
    ['FW','Cyle Larin',1995,'Southampton FC',92],
    ['FW','Jonathan David',2000,'Juventus FC',79],
    ['MF','Liam Millar',1999,'Hull City FC',42],
    ['FW','Tani Oluwaseyi',2000,'Villarreal CF',26],
    ['DF','Derek Cornelius',1997,'Rangers FC',46],
    ['MF','Jacob Shaffelburg',1999,'Los Angeles FC',33],
    ['DF','Moïse Bombito',2000,'OGC Nice',21],
    ['GK','Maxime Crépeau',1994,'Orlando City SC',34],
    ['MF','Tajon Buchanan',1999,'Villarreal CF',62],
    ['GK','Owen Goodman',2003,'Barnsley',0],
    ['DF','Alphonso Davies',2000,'FC Bayern München',58],
    ['MF','Ali Ahmed',2000,'Norwich City FC',26],
    ['MF','Jonathan Osorio',1992,'Toronto FC',92],
    ['DF','Richie Laryea',1995,'Toronto FC',78],
    ['DF','Niko Sigur',2003,'HNK Hajduk Split',20],
    ['FW','Promise David',2001,'Royale Union Saint-Gilloise',11],
    ['MF','Nathan Saliba',2004,'RSC Anderlecht',16],
],

'Kolumbien': [
    ['GK','David Ospina',1988,'Atlético Nacional',130],
    ['DF','Daniel Muñoz',1996,'Crystal Palace FC',47],
    ['DF','Jhon Lucumí',1998,'Bologna FC',38],
    ['DF','Santiago Arias',1992,'CA Independiente',68],
    ['MF','Kevin Castaño',2000,'CA River Plate',26],
    ['MF','Richard Ríos',2000,'SL Benfica',33],
    ['FW','Luis Díaz',1997,'FC Bayern München',75],
    ['MF','Jorge Carrascal',1998,'CR Flamengo',25],
    ['FW','Jhon Córdoba',1993,'FC Krasnodar',21],
    ['MF','James Rodríguez',1991,'Minnesota United FC',127],
    ['MF','Jhon Arias',1997,'SE Palmeiras',39],
    ['GK','Camilo Vargas',1989,'Atlas FC',43],
    ['DF','Yerry Mina',1994,'Cagliari',54],
    ['DF','Gustavo Puerta',2003,'Racing Santander',7],
    ['MF','Juan Portilla',1998,'Athletico Paranaense',10],
    ['MF','Jefferson Lerma',1994,'Crystal Palace FC',66],
    ['DF','Johan Mojica',1992,'RCD Mallorca',46],
    ['DF','Willer Ditta',1998,'CF Cruz Azul',5],
    ['FW','Cucho Hernández',1999,'Real Betis',10],
    ['MF','Juan Quintero',1993,'CA River Plate',49],
    ['FW','Jaminton Campaz',2000,'CA Rosario Central',11],
    ['DF','Deiver Machado',1993,'FC Nantes',15],
    ['DF','Davinson Sánchez',1996,'Galatasaray SK',80],
    ['GK','Álvaro Montero',1995,'CA Vélez Sarsfield',12],
    ['FW','Luis Suárez',1997,'Sporting CP',13],
    ['FW','Andrés Gómez',2002,'CR Vasco da Gama',9],
],

'Kongo DR': [
    ['GK','Lionel Mpasi',1994,'Le Havre AC',29],
    ['DF','Aaron Wan-Bissaka',1997,'West Ham United FC',13],
    ['DF','Steve Kapuadi',1998,'Widzew Łódź',4],
    ['DF','Axel Tuanzebe',1997,'Burnley FC',14],
    ['DF','Dylan Batubinsika',1996,'AEL FC',15],
    ['MF','Ngal\'ayel Mukau',2004,'Lille OSC',15],
    ['MF','Nathanaël Mbuku',2002,'Montpellier HSC',19],
    ['MF','Samuel Moutoussamy',1996,'Atromitos FC',59],
    ['FW','Brian Cipenga',1998,'CD Castellón',8],
    ['MF','Théo Bongonda',1995,'FC Spartak Moscow',38],
    ['FW','Gaël Kakuta',1991,'AEL FC',31],
    ['DF','Joris Kayembe',1994,'KRC Genk',27],
    ['FW','Meschack Elia',1997,'Alanyaspor',68],
    ['MF','Noah Sadiki',2004,'Sunderland AFC',21],
    ['MF','Aaron Tshibola',1995,'Kilmarnock FC',17],
    ['GK','Timothy Fayulu',1999,'FC Noah',3],
    ['FW','Cedric Bakambu',1991,'Real Betis',71],
    ['MF','Charles Pickel',1997,'RCD Espanyol',35],
    ['FW','Fiston Mayele',1994,'Pyramids FC',36],
    ['FW','Yoane Wissa',1996,'Newcastle United FC',39],
    ['GK','Matthieu Epolo',2005,'Standard Liège',1],
    ['DF','Chancel Mbemba',1994,'Lille OSC',110],
    ['FW','Simon Banza',1996,'Al Jazira',16],
    ['DF','Gédéon Kalulu',1997,'Aris Limassol FC',29],
    ['MF','Edo Kayembe',1998,'Watford FC',43],
    ['DF','Arthur Masuaku',1993,'RC Lens',45],
],

'Elfenbeinküste': [
    ['GK','Yahia Fofana',2000,'Çaykur Rizespor',38],
    ['DF','Ousmane Diomande',2003,'Sporting CP',16],
    ['DF','Ghislain Konan',1995,'Gil Vicente FC',56],
    ['MF','Jean Michaël Seri',1991,'NK Maribor',65],
    ['DF','Wilfried Singo',2000,'Galatasaray SK',37],
    ['MF','Seko Fofana',1995,'FC Porto',34],
    ['DF','Odilon Kossounou',2001,'Atalanta Bergamo',38],
    ['MF','Franck Kessié',1996,'Al Ahli FC',106],
    ['FW','Ange-Yoan Bonny',2003,'FC Internazionale Milano',3],
    ['FW','Simon Adingra',2002,'AS Monaco',30],
    ['FW','Yan Diomande',2006,'RB Leipzig',12],
    ['FW','Elye Wahi',2003,'OGC Nice',3],
    ['DF','Christopher Operi',1997,'Başakşehir FK',12],
    ['FW','Oumar Diakité',2003,'Cercle Brugge',29],
    ['FW','Amad Diallo',2002,'Manchester United FC',21],
    ['GK','Mohamed Koné',2002,'Sporting Charleroi',0],
    ['DF','Guéla Doué',2002,'RC Strasbourg',22],
    ['MF','Ibrahim Sangaré',1997,'Nottingham Forest FC',57],
    ['FW','Nicolas Pépé',1995,'Villarreal CF',58],
    ['DF','Emmanuel Agbadou',1997,'Beşiktaş JK',23],
    ['DF','Evan Ndicka',1999,'AS Roma',29],
    ['FW','Evann Guessand',2001,'Crystal Palace FC',22],
    ['GK','Alban Lafont',1999,'Panathinaikos FC',4],
    ['FW','Bazoumana Touré',2006,'TSG Hoffenheim',7],
    ['MF','Parfait Guiagon',2001,'Sporting Charleroi',5],
    ['MF','Christ Inao Oulaï',2006,'Trabzonspor',11],
],

'Kroatien': [
    ['GK','Dominik Livaković',1995,'GNK Dinamo Zagreb',76],
    ['DF','Josip Stanišić',2000,'FC Bayern München',32],
    ['DF','Marin Pongračić',1997,'ACF Fiorentina',20],
    ['DF','Joško Gvardiol',2002,'Manchester City FC',49],
    ['DF','Duje Ćaleta-Car',1996,'Real Sociedad',38],
    ['DF','Josip Šutalo',2000,'AFC Ajax',34],
    ['MF','Nikola Moro',1998,'Bologna FC',10],
    ['MF','Mateo Kovačić',1994,'Manchester City FC',114],
    ['FW','Andrej Kramarić',1991,'TSG Hoffenheim',117],
    ['MF','Luka Modrić',1985,'AC Milan',199],
    ['FW','Ante Budimir',1991,'CA Osasuna',38],
    ['GK','Ivor Pandur',2000,'Hull City FC',0],
    ['MF','Nikola Vlašić',1997,'Torino FC',64],
    ['FW','Ivan Perišić',1989,'PSV Eindhoven',155],
    ['MF','Mario Pašalić',1995,'Atalanta Bergamo',86],
    ['MF','Martin Baturina',2003,'Como',20],
    ['MF','Petar Sučić',2003,'FC Internazionale Milano',18],
    ['DF','Kristijan Jakić',1997,'FC Augsburg',17],
    ['MF','Toni Fruk',2001,'HNK Rijeka',7],
    ['FW','Igor Matanović',2003,'SC Freiburg',10],
    ['MF','Luka Sučić',2002,'Real Sociedad',21],
    ['DF','Luka Vušković',2007,'Hamburger SV',6],
    ['GK','Dominik Kotarski',2000,'FC København',4],
    ['FW','Marco Pašalić',2000,'Orlando City SC',16],
    ['DF','Martin Erlić',1998,'FC Midtjylland',13],
    ['FW','Petar Musa',1998,'FC Dallas',12],
],

'Curaçao': [
    ['GK','Eloy Room',1989,'Miami FC',74],
    ['DF','Shurandy Sambo',2001,'Sparta Rotterdam',8],
    ['DF','Juriën Gaari',1993,'Abha Club',61],
    ['DF','Roshon van Eijma',1998,'RKC Waalwijk',29],
    ['DF','Sherel Floranus',1998,'PEC Zwolle',29],
    ['MF','Godfried Roemeratoe',1999,'RKC Waalwijk',30],
    ['MF','Juninho Bacuna',1997,'FC Volendam',52],
    ['MF','Livano Comenencia',2004,'FC Zürich',22],
    ['FW','Jürgen Locadia',1993,'Miami FC',15],
    ['MF','Leandro Bacuna',1991,'Iğdır FK',74],
    ['FW','Jeremy Antonisse',2002,'AE Kifisia FC',28],
    ['FW','Sontje Hansen',2002,'Middlesbrough FC',7],
    ['MF','Tyrese Noslin',2002,'SC Telstar',7],
    ['FW','Kenji Gorré',1994,'Maccabi Haifa FC',39],
    ['MF','Ar\'jany Martha',2003,'Rotherham United FC',9],
    ['FW','Jearl Margaritha',2000,'SK Beveren',24],
    ['FW','Brandley Kuwas',1992,'FC Volendam',36],
    ['DF','Armando Obispo',1999,'PSV Eindhoven',8],
    ['FW','Gervane Kastaneer',1996,'Terengganu FC',31],
    ['DF','Joshua Brenet',1994,'Kayserispor',19],
    ['MF','Tahith Chong',1999,'Sheffield United FC',8],
    ['MF','Kevin Felida',1999,'FC Den Bosch',19],
    ['DF','Riechedly Bazoer',1996,'Konyaspor',6],
    ['DF','Deveron Fonville',2003,'NEC Nijmegen',4],
    ['GK','Tyrick Bodak',2002,'SC Telstar',4],
    ['GK','Trevor Doornbusch',1999,'VVV Venlo',8],
],

'Tschechien': [
    ['GK','Matěj Kovář',2000,'PSV Eindhoven',22],
    ['DF','David Zima',2000,'SK Slavia Praha',26],
    ['DF','Tomáš Holeš',1993,'SK Slavia Praha',42],
    ['DF','Robin Hranáč',2000,'TSG Hoffenheim',16],
    ['DF','Vladimír Coufal',1992,'TSG Hoffenheim',64],
    ['DF','Štěpán Chaloupek',2003,'SK Slavia Praha',6],
    ['DF','Ladislav Krejčí',1999,'Wolverhampton Wanderers FC',29],
    ['MF','Vladimír Darida',1990,'FC Hradec Králové',80],
    ['FW','Adam Hložek',2002,'TSG Hoffenheim',45],
    ['FW','Patrik Schick',1996,'Bayer 04 Leverkusen',55],
    ['FW','Jan Kuchta',1997,'AC Sparta Praha',31],
    ['MF','Lukáš Červ',2001,'FC Viktoria Plzeň',18],
    ['FW','Mojmír Chytil',1999,'SK Slavia Praha',23],
    ['DF','David Jurásek',2000,'SK Slavia Praha',18],
    ['FW','Pavel Šulc',2000,'Olympique Lyonnais',23],
    ['GK','Jindřich Staněk',1996,'SK Slavia Praha',14],
    ['MF','Lukáš Provod',1996,'SK Slavia Praha',40],
    ['MF','Michal Sadílek',1999,'SK Slavia Praha',37],
    ['FW','Tomáš Chorý',1995,'SK Slavia Praha',23],
    ['DF','Jaroslav Zelený',1992,'AC Sparta Praha',25],
    ['DF','David Douděra',1998,'SK Slavia Praha',17],
    ['MF','Tomáš Souček',1995,'West Ham United FC',92],
    ['GK','Lukáš Horníček',2002,'SC Braga',1],
    ['MF','Alexandr Sojka',2003,'FC Viktoria Plzeň',4],
    ['MF','Hugo Sochůrek',2008,'AC Sparta Praha',1],
    ['FW','Denis Višinský',2003,'FC Viktoria Plzeň',2],
],

'Ecuador': [
    ['GK','Hernán Galíndez',1987,'CA Huracán',37],
    ['DF','Félix Torres',1997,'SC Internacional',49],
    ['DF','Piero Hincapié',2002,'Arsenal FC',54],
    ['DF','Joel Ordóñez',2004,'Club Brugge',18],
    ['MF','Jordy Alcívar',1999,'Independiente del Valle',12],
    ['DF','Willian Pacho',2001,'Paris Saint-Germain',36],
    ['DF','Pervis Estupiñán',1998,'AC Milan',55],
    ['MF','Anthony Valencia',2003,'Royal Antwerp FC',3],
    ['FW','John Yeboah',2000,'Venezia FC',24],
    ['MF','Kendry Páez',2007,'CA River Plate',26],
    ['FW','Kevin Rodríguez',2000,'Royale Union Saint-Gilloise',33],
    ['GK','Moisés Ramírez',2000,'AE Kifisia FC',7],
    ['FW','Enner Valencia',1989,'CF Pachuca',107],
    ['MF','Alan Minda',2003,'Atlético Mineiro',21],
    ['MF','Pedro Vite',2002,'Pumas UNAM',19],
    ['FW','Jordy Caicedo',1997,'CA Huracán',21],
    ['DF','Ángelo Preciado',1998,'Atlético Mineiro',58],
    ['MF','Denil Castillo',2004,'FC Midtjylland',5],
    ['FW','Gonzalo Plata',2000,'CR Flamengo',52],
    ['FW','Nilson Angulo',2003,'Sunderland AFC',16],
    ['MF','Alan Franco',1998,'Atlético Mineiro',60],
    ['GK','Gonzalo Valle',1996,'LDU Quito',4],
    ['MF','Moisés Caicedo',2001,'Chelsea FC',63],
    ['FW','Jeremy Arévalo',2005,'VfB Stuttgart',4],
    ['DF','Jackson Porozo',2000,'Club Tijuana',10],
    ['DF','Yaimar Medina',2004,'KRC Genk',6],
],

'Ägypten': [
    ['GK','Mohamed Elshenawy',1988,'Al Ahly FC',77],
    ['DF','Yasser Ibrahim',1993,'Al Ahly FC',19],
    ['DF','Mohamed Hany',1996,'Al Ahly FC',44],
    ['DF','Hossam Abdelmaguid',2001,'Zamalek SC',13],
    ['DF','Ramy Rabia',1993,'Al Ain FC',48],
    ['DF','Mohamed Abdelmoneim',1999,'OGC Nice',36],
    ['FW','Trezeguet',1994,'Al Ahly FC',96],
    ['MF','Emam Ashour',1998,'Al Ahly FC',30],
    ['FW','Hamza Abdelkarim',2008,'FC Barcelona',3],
    ['FW','Mohamed Salah',1992,'Liverpool FC',117],
    ['MF','Mostafa Zico',1997,'Pyramids FC',3],
    ['FW','Haissem Hassan',2002,'Real Oviedo',4],
    ['DF','Ahmed Fatouh',1998,'Zamalek SC',40],
    ['MF','Hamdy Fathy',1994,'Al Wakrah SC',65],
    ['DF','Karim Hafez',1996,'Pyramids FC',10],
    ['GK','Mahdy Soliman',1987,'Zamalek SC',0],
    ['MF','Mohanad Lashin',1996,'Pyramids FC',24],
    ['MF','Nabil Donga',1996,'Al Najmah SC',12],
    ['MF','Marawan Attia',1998,'Al Ahly FC',36],
    ['FW','Ibrahim Adel',2001,'FC Nordsjælland',25],
    ['MF','Mahmoud Saber',2001,'ZED FC',15],
    ['FW','Omar Marmoush',1999,'Manchester City FC',51],
    ['GK','Mostafa Shoubir',2000,'Al Ahly FC',11],
    ['DF','Tarek Alaa',2002,'ZED FC',3],
    ['FW','Zizo',1996,'Al Ahly FC',65],
    ['GK','Mohamed Alaa',1999,'El Gouna FC',0],
],

'England': [
    ['GK','Jordan Pickford',1994,'Everton FC',85],
    ['DF','Ezri Konsa',1997,'Aston Villa FC',21],
    ['DF','Nico O\'Reilly',2005,'Manchester City FC',6],
    ['MF','Declan Rice',1999,'Arsenal FC',74],
    ['DF','John Stones',1994,'Manchester City FC',90],
    ['DF','Marc Guéhi',2000,'Manchester City FC',30],
    ['FW','Bukayo Saka',2001,'Arsenal FC',50],
    ['MF','Elliot Anderson',2002,'Nottingham Forest FC',10],
    ['FW','Harry Kane',1993,'FC Bayern München',115],
    ['MF','Jude Bellingham',2003,'Real Madrid C.F.',49],
    ['FW','Marcus Rashford',1997,'FC Barcelona',73],
    ['DF','Trevoh Chalobah',1999,'Chelsea FC',1],
    ['GK','Dean Henderson',1997,'Crystal Palace FC',5],
    ['MF','Jordan Henderson',1990,'Brentford FC',90],
    ['DF','Dan Burn',1992,'Newcastle United FC',8],
    ['MF','Kobbie Mainoo',2005,'Manchester United FC',14],
    ['MF','Morgan Rogers',2002,'Aston Villa FC',16],
    ['FW','Anthony Gordon',2001,'Newcastle United FC',20],
    ['FW','Ollie Watkins',1995,'Aston Villa FC',22],
    ['FW','Noni Madueke',2002,'Arsenal FC',12],
    ['MF','Eberechi Eze',1998,'Arsenal FC',17],
    ['FW','Ivan Toney',1996,'Al Ahli FC',8],
    ['GK','James Trafford',2002,'Manchester City FC',2],
    ['DF','Reece James',1999,'Chelsea FC',25],
    ['DF','Djed Spence',2000,'Tottenham Hotspur FC',7],
    ['DF','Jarell Quansah',2003,'Bayer 04 Leverkusen',3],
],

'Frankreich': [
    ['GK','Brice Samba',1994,'Stade Rennais FC',4],
    ['DF','Malo Gusto',2003,'Chelsea FC',11],
    ['DF','Lucas Digne',1993,'Aston Villa FC',58],
    ['DF','Dayot Upamecano',1998,'FC Bayern München',39],
    ['DF','Jules Koundé',1998,'FC Barcelona',49],
    ['MF','Manu Koné',2001,'AS Roma',14],
    ['FW','Ousmane Dembélé',1997,'Paris Saint-Germain',60],
    ['MF','Aurélien Tchouaméni',2000,'Real Madrid C.F.',47],
    ['FW','Marcus Thuram',1997,'FC Internazionale Milano',34],
    ['FW','Kylian Mbappé',1998,'Real Madrid C.F.',99],
    ['FW','Michael Olise',2001,'FC Bayern München',18],
    ['FW','Bradley Barcola',2002,'Paris Saint-Germain',21],
    ['MF','N\'Golo Kanté',1991,'Fenerbahçe SK',69],
    ['MF','Adrien Rabiot',1995,'AC Milan',60],
    ['DF','Ibrahima Konaté',1999,'Liverpool FC',28],
    ['GK','Mike Maignan',1995,'AC Milan',41],
    ['DF','William Saliba',2001,'Arsenal FC',33],
    ['MF','Warren Zaïre-Emery',2006,'Paris Saint-Germain',11],
    ['DF','Théo Hernandez',1997,'Al Hilal SC',45],
    ['FW','Désiré Doué',2005,'Paris Saint-Germain',8],
    ['DF','Lucas Hernandez',1996,'Paris Saint-Germain',42],
    ['FW','Jean-Philippe Mateta',1997,'Crystal Palace FC',4],
    ['GK','Robin Risser',2004,'RC Lens',0],
    ['MF','Rayan Cherki',2003,'Manchester City FC',8],
    ['MF','Maghnes Akliouche',2002,'AS Monaco',9],
    ['DF','Maxence Lacroix',2000,'Crystal Palace FC',4],
],

'Deutschland': [
    ['GK','Manuel Neuer',1986,'FC Bayern München',126],
    ['DF','Antonio Rüdiger',1993,'Real Madrid C.F.',84],
    ['DF','Waldemar Anton',1996,'Borussia Dortmund',14],
    ['DF','Jonathan Tah',1996,'FC Bayern München',49],
    ['MF','Aleksandar Pavlović',2004,'FC Bayern München',13],
    ['MF','Joshua Kimmich',1995,'FC Bayern München',112],
    ['FW','Kai Havertz',1999,'Arsenal FC',60],
    ['MF','Leon Goretzka',1995,'FC Bayern München',72],
    ['MF','Jamie Leweling',2001,'VfB Stuttgart',6],
    ['MF','Jamal Musiala',2003,'FC Bayern München',44],
    ['FW','Nick Woltemade',2002,'Newcastle United FC',11],
    ['GK','Oliver Baumann',1990,'TSG Hoffenheim',13],
    ['MF','Pascal Groß',1991,'Brighton & Hove Albion FC',18],
    ['FW','Maximilian Beier',2002,'Borussia Dortmund',9],
    ['DF','Nico Schlotterbeck',1999,'Borussia Dortmund',29],
    ['MF','Angelo Stiller',2001,'VfB Stuttgart',8],
    ['MF','Florian Wirtz',2003,'Liverpool FC',43],
    ['DF','Nathaniel Brown',2003,'Eintracht Frankfurt',7],
    ['MF','Leroy Sané',1996,'Galatasaray SK',78],
    ['MF','Nadiem Amiri',1996,'1. FSV Mainz 05',12],
    ['GK','Alexander Nübel',1996,'VfB Stuttgart',3],
    ['DF','David Raum',1998,'RB Leipzig',38],
    ['MF','Felix Nmecha',2000,'Borussia Dortmund',10],
    ['DF','Malick Thiaw',2001,'Newcastle United FC',5],
    ['MF','Lennart Karl',2008,'FC Bayern München',3],
    ['FW','Deniz Undav',1996,'VfB Stuttgart',11],
],

'Ghana': [
    ['GK','Lawrence Zigi',1996,'FC St. Gallen',31],
    ['DF','Alidu Seidu',2000,'Stade Rennais FC',24],
    ['MF','Caleb Yirenkyi',2006,'FC Nordsjælland',12],
    ['DF','Jonas Adjetey',2003,'VfL Wolfsburg',11],
    ['MF','Thomas Partey',1993,'Villarreal CF',59],
    ['DF','Abdul Mumin',1998,'Rayo Vallecano',5],
    ['FW','Abdul Fatawu',2004,'Leicester City FC',29],
    ['MF','Kwasi Sibo',1998,'Real Oviedo',9],
    ['FW','Jordan Ayew',1991,'Leicester City FC',121],
    ['FW','Brandon Thomas-Asante',1998,'Coventry City FC',9],
    ['MF','Antoine Semenyo',2000,'Manchester City FC',35],
    ['GK','Joseph Anang',2000,'St Patrick\'s Athletic FC',1],
    ['FW','Christopher Bonsu Baah',2004,'Al Qadsiah FC',9],
    ['DF','Gideon Mensah',1998,'AJ Auxerre',41],
    ['MF','Elisha Owusu',1997,'AJ Auxerre',21],
    ['GK','Benjamin Asare',1992,'Hearts of Oak SC',14],
    ['DF','Baba Rahman',1994,'PAOK Saloniki',53],
    ['DF','Jerome Opoku',1998,'Başakşehir FK',12],
    ['FW','Inaki Williams',1994,'Athletic Club',26],
    ['MF','Augustine Boakye',2000,'AS Saint-Etienne',0],
    ['DF','Kojo Oppong',2004,'OGC Nice',4],
    ['FW','Kamaldeen Sulemana',2002,'Atalanta Bergamo',29],
    ['DF','Derrick Luckassen',1995,'Pafos FC',1],
    ['FW','Ernest Nuamah',2003,'Olympique Lyonnais',20],
    ['FW','Prince Adu',2003,'FC Viktoria Plzeň',6],
    ['DF','Marvin Senaya',2001,'AJ Auxerre',3],
],

'Haiti': [
    ['GK','Johny Placide',1988,'SC Bastia',85],
    ['DF','Carlens Arcus',1996,'Angers SCO',58],
    ['DF','Keeto Thermoncy',2006,'BSC Young Boys',1],
    ['DF','Ricardo Adé',1990,'LDU Quito',63],
    ['DF','Hannes Delcroix',1999,'FC Lugano',9],
    ['MF','Carl Sainté',2002,'El Paso Locomotive FC',26],
    ['FW','Derrick Etienne Jr.',1996,'Toronto FC',51],
    ['DF','Martin Expérience',1999,'AS Nancy',23],
    ['FW','Duckens Nazon',1994,'Esteghlal Tehran FC',83],
    ['MF','Jean-Ricner Bellegarde',1998,'Wolverhampton Wanderers FC',12],
    ['FW','Louicius Deedson',2001,'FC Dallas',34],
    ['GK','Alexandre Pierre',2001,'FC Sochaux-Montbéliard',17],
    ['DF','Duke Lacroix',1993,'Colorado Springs Switchbacks FC',16],
    ['DF','Garven Metusala',1999,'Colorado Springs Switchbacks FC',15],
    ['FW','Ruben Providence',2001,'Almere City FC',17],
    ['FW','Lenny Joseph',2000,'Ferencvárosi TC',4],
    ['MF','Danley Jean Jacques',2000,'Philadelphia Union',33],
    ['FW','Wilson Isidor',2000,'Sunderland AFC',6],
    ['FW','Yassin Fortune',1999,'FC Vizela',5],
    ['FW','Frantzdy Pierrot',1995,'Çaykur Rizespor',55],
    ['FW','Josué Casimir',2001,'AJ Auxerre',9],
    ['DF','Jean-Kévin Duverne',1997,'KAA Gent',18],
    ['GK','Josué Duverger',2000,'FC Cosmos Koblenz',7],
    ['DF','Wilguens Paugain',2001,'SV Zulte Waregem',8],
    ['MF','Dominique Simon',2000,'FC Tatran Prešov',3],
    ['MF','Woodensky Pierre',2004,'Violette AC',1],
],

# ── Wikipedia-Teams ───────────────────────────────────────────────────────────

'Mexiko': [
    ['GK','Guillermo Ochoa',1985,'AEL Limassol',152],
    ['GK','Raúl Rangel',2000,'Guadalajara',13],
    ['GK','Carlos Acevedo',1996,'Santos Laguna',7],
    ['DF','Jesús Gallardo',1994,'Toluca',120],
    ['DF','César Montes',1997,'Lokomotiv Moscow',66],
    ['DF','Jorge Sánchez',1997,'PAOK',58],
    ['DF','Johan Vásquez',1998,'Genoa',45],
    ['DF','Israel Reyes',2000,'América',33],
    ['DF','Mateo Chávez',2004,'AZ',9],
    ['MF','Edson Álvarez',1997,'Fenerbahçe',97],
    ['MF','Orbelín Pineda',1996,'AEK Athens',91],
    ['MF','Roberto Alvarado',1998,'Guadalajara',66],
    ['MF','Luis Romo',1995,'Guadalajara',62],
    ['MF','Luis Chávez',1996,'Dynamo Moscow',44],
    ['MF','Érik Lira',2000,'Cruz Azul',24],
    ['MF','Gilberto Mora',2008,'Tijuana',7],
    ['MF','Brian Gutiérrez',2003,'Guadalajara',6],
    ['MF','Obed Vargas',2005,'Atlético de Madrid',6],
    ['MF','Álvaro Fidalgo',1997,'Real Betis',3],
    ['FW','Raúl Jiménez',1991,'Fulham',123],
    ['FW','Alexis Vega',1997,'Toluca',51],
    ['FW','Santiago Giménez',2001,'AC Milan',47],
    ['FW','César Huerta',2000,'Anderlecht',26],
    ['FW','Julián Quiñones',1997,'Al Qadsiah',21],
    ['FW','Guillermo Martínez',1995,'UNAM',11],
    ['FW','Armando González',2003,'Guadalajara',7],
],

'Südafrika': [
    ['GK','Ronwen Williams',1992,'Mamelodi Sundowns',62],
    ['GK','Ricardo Goss',1994,'Siwelele',4],
    ['GK','Sipho Chaine',1996,'Orlando Pirates',3],
    ['DF','Aubrey Modiba',1995,'Mamelodi Sundowns',44],
    ['DF','Khuliso Mudau',1995,'Mamelodi Sundowns',32],
    ['DF','Nkosinathi Sibisi',1995,'Orlando Pirates',19],
    ['DF','Mbekezeli Mbokazi',2005,'Chicago Fire FC',10],
    ['DF','Ime Okon',2004,'Hannover 96',7],
    ['DF','Samukele Kabini',2004,'Molde',5],
    ['DF','Khulumani Ndamane',2004,'Mamelodi Sundowns',5],
    ['DF','Thabang Matuludi',1999,'Polokwane City',2],
    ['DF','Kamogelo Sebelebele',2002,'Orlando Pirates',2],
    ['DF','Bradley Cross',2001,'Kaizer Chiefs',0],
    ['DF','Olwethu Makhanya',2004,'Philadelphia Union',0],
    ['MF','Teboho Mokoena',1997,'Mamelodi Sundowns',51],
    ['MF','Sphephelo Sithole',1999,'Tondela',27],
    ['MF','Thalente Mbatha',2000,'Orlando Pirates',14],
    ['MF','Jayden Adams',2001,'Mamelodi Sundowns',4],
    ['FW','Themba Zwane',1989,'Mamelodi Sundowns',53],
    ['FW','Lyle Foster',2000,'Burnley',26],
    ['FW','Evidence Makgopa',2000,'Orlando Pirates',26],
    ['FW','Oswin Appollis',2001,'Orlando Pirates',25],
    ['FW','Iqraam Rayners',1995,'Mamelodi Sundowns',13],
    ['FW','Relebohile Mofokeng',2004,'Orlando Pirates',12],
    ['FW','Thapelo Maseko',2003,'AEL Limassol',9],
    ['FW','Tshepang Moremi',2000,'Orlando Pirates',9],
],

'Südkorea': [
    ['GK','Kim Seung-gyu',1990,'FC Tokyo',86],
    ['GK','Jo Hyeon-woo',1991,'Ulsan HD',48],
    ['GK','Song Bum-keun',1997,'Jeonbuk Hyundai Motors',2],
    ['DF','Kim Min-jae',1996,'Bayern Munich',78],
    ['DF','Kim Moon-hwan',1995,'Daejeon Hana Citizen',35],
    ['DF','Seol Young-woo',1998,'Red Star Belgrade',33],
    ['DF','Lee Tae-seok',2002,'Austria Wien',14],
    ['DF','Park Jin-seob',1995,'Zhejiang',13],
    ['DF','Kim Tae-hyeon',2000,'Kashima Antlers',7],
    ['DF','Lee Han-beom',2002,'Midtjylland',7],
    ['DF','Jens Castrop',2003,'Borussia Mönchengladbach',6],
    ['DF','Lee Ki-hyuk',2000,'Gangwon FC',2],
    ['DF','Cho Wi-je',2001,'Jeonbuk Hyundai Motors',0],
    ['MF','Lee Jae-sung',1992,'1. FSV Mainz 05',104],
    ['MF','Hwang Hee-chan',1996,'Wolverhampton Wanderers',78],
    ['MF','Hwang In-beom',1996,'Feyenoord',72],
    ['MF','Lee Kang-in',2001,'Paris Saint-Germain',46],
    ['MF','Paik Seung-ho',1997,'Birmingham City',26],
    ['MF','Kim Jin-gyu',1997,'Jeonbuk Hyundai Motors',21],
    ['MF','Lee Dong-gyeong',1997,'Ulsan HD',17],
    ['MF','Bae Jun-ho',2003,'Stoke City',13],
    ['MF','Eom Ji-sung',2002,'Swansea City',9],
    ['MF','Yang Hyun-jun',2002,'Celtic',8],
    ['FW','Son Heung-min',1992,'Los Angeles FC',143],
    ['FW','Cho Gue-sung',1998,'Midtjylland',43],
    ['FW','Oh Hyeon-gyu',2001,'Beşiktaş',26],
],

'Katar': [
    ['GK','Mahmud Abunada',2000,'Al-Rayyan',4],
    ['DF','Pedro Miguel',1990,'Al-Sadd',98],
    ['DF','Lucas Mendes',1990,'Al-Wakrah',25],
    ['DF','Issa Laye',1997,'Al-Arabi',3],
    ['MF','Jassem Gaber',2002,'Al-Rayyan',31],
    ['MF','Abdulaziz Hatem',1990,'Al-Rayyan',117],
    ['FW','Ahmed Alaaeldin',1993,'Al-Rayyan',67],
    ['FW','Edmilson Junior',1994,'Al-Duhail',15],
    ['FW','Mohammed Muntari',1993,'Al-Gharafa',67],
    ['FW','Hassan Al-Haydos',1990,'Al-Sadd',185],
    ['FW','Akram Afif',1996,'Al-Sadd',124],
    ['MF','Karim Boudiaf',1990,'Al-Duhail',117],
    ['DF','Ayoub Al-Oui',2005,'Al-Gharafa',5],
    ['DF','Homam Ahmed',1999,'Cultural Leonesa',67],
    ['FW','Yusuf Abdurisag',1999,'Al-Wakrah',38],
    ['DF','Boualem Khoukhi',1990,'Al-Sadd',115],
    ['FW','Ahmed Al-Ganehi',2000,'Al-Gharafa',13],
    ['DF','Sultan Al-Brake',1996,'Al-Duhail',16],
    ['FW','Almoez Ali',1996,'Al-Duhail',115],
    ['MF','Ahmed Fathy',1993,'Al-Arabi',47],
    ['GK','Salah Zakaria',1999,'Al-Duhail',8],
    ['GK','Meshaal Barsham',1998,'Al-Sadd',52],
    ['MF','Assim Madibo',1996,'Al-Wakrah',50],
    ['FW','Tahsin Jamshid',2006,'Al-Duhail',2],
    ['DF','Al-Hashmi Al-Hussain',2003,'Al-Arabi',7],
    ['MF','Mohamed Al-Mannai',2003,'Al-Shamal',9],
],

'Schweiz': [
    ['GK','Gregor Kobel',1997,'Borussia Dortmund',20],
    ['DF','Miro Muheim',1998,'Hamburger SV',9],
    ['DF','Silvan Widmer',1993,'1. FSV Mainz 05',59],
    ['DF','Nico Elvedi',1996,'Borussia Mönchengladbach',66],
    ['DF','Manuel Akanji',1995,'FC Internazionale Milano',80],
    ['MF','Denis Zakaria',1996,'AS Monaco',64],
    ['FW','Breel Embolo',1997,'Stade Rennais FC',86],
    ['MF','Remo Freuler',1992,'Bologna FC',87],
    ['MF','Johan Manzambi',2005,'SC Freiburg',11],
    ['MF','Granit Xhaka',1992,'Sunderland',145],
    ['FW','Dan Ndoye',2000,'Nottingham Forest',30],
    ['GK','Yvon Mvogo',1994,'Lorient',13],
    ['DF','Ricardo Rodriguez',1992,'Real Betis',137],
    ['MF','Ardon Jashari',2002,'AC Milan',7],
    ['MF','Djibril Sow',1997,'Sevilla FC',51],
    ['MF','Christian Fassnacht',1993,'BSC Young Boys',22],
    ['FW','Rubén Vargas',1998,'Sevilla FC',61],
    ['DF','Eray Cömert',1998,'Valencia CF',21],
    ['FW','Noah Okafor',2000,'Leeds United',24],
    ['MF','Michel Aebischer',1997,'AC Pisa',39],
    ['GK','Marvin Keller',2002,'BSC Young Boys',1],
    ['MF','Fabian Rieder',2002,'FC Augsburg',27],
    ['FW','Zeki Amdouni',2000,'Burnley',28],
    ['DF','Aurèle Amenda',2003,'Eintracht Frankfurt',6],
    ['DF','Luca Jaquez',2003,'VfB Stuttgart',3],
    ['FW','Cedric Itten',1996,'Fortuna Düsseldorf',14],
],

'Marokko': [
    ['GK','Yassine Bounou',1991,'Al-Hilal',89],
    ['GK','Munir Mohamedi',1989,'RS Berkane',51],
    ['GK','Ahmed Reda Tagnaouti',1996,'AS FAR',3],
    ['DF','Achraf Hakimi',1998,'Paris Saint-Germain',95],
    ['DF','Nayef Aguerd',1996,'Olympique Marseille',64],
    ['DF','Noussair Mazraoui',1997,'Manchester United FC',43],
    ['DF','Youssef Belammari',1998,'Al Ahly',16],
    ['DF','Anass Salah-Eddine',2002,'PSV Eindhoven',8],
    ['DF','Chadi Riad',2003,'Crystal Palace FC',4],
    ['DF','Issa Diop',1997,'Fulham FC',2],
    ['DF','Zakaria El Ouahdi',2001,'KRC Genk',2],
    ['DF','Redouane Halhal',2003,'Mechelen',1],
    ['MF','Sofyan Amrabat',1996,'Real Betis',73],
    ['MF','Azzedine Ounahi',2000,'Girona FC',47],
    ['MF','Bilal El Khannouss',2004,'VfB Stuttgart',35],
    ['MF','Ismael Saibari',2001,'PSV Eindhoven',28],
    ['MF','Neil El Aynaoui',2001,'AS Roma',15],
    ['MF','Samir El Mourabet',2006,'RC Strasbourg',2],
    ['MF','Ayyoub Bouaddi',2007,'Lille OSC',1],
    ['FW','Ayoub El Kaabi',1993,'Olympiacos FC',57],
    ['FW','Soufiane Rahimi',1996,'Al-Ain',35],
    ['FW','Abde Ezzalzouli',2001,'Real Betis',35],
    ['FW','Brahim Díaz',1999,'Real Madrid C.F.',24],
    ['FW','Chemsdine Talbi',2005,'Sunderland AFC',5],
    ['FW','Gessime Yassine',2005,'RC Strasbourg',3],
    ['FW','Ayoube Amaimouni',2004,'Eintracht Frankfurt',0],
],

'Schottland': [
    ['GK','Craig Gordon',1982,'Heart of Midlothian',84],
    ['GK','Angus Gunn',1996,'Nottingham Forest FC',21],
    ['GK','Liam Kelly',1996,'Rangers FC',3],
    ['DF','Andy Robertson',1994,'Liverpool FC',93],
    ['DF','Grant Hanley',1991,'Hibernian',67],
    ['DF','Kieran Tierney',1997,'Celtic FC',55],
    ['DF','Scott McKenna',1996,'GNK Dinamo Zagreb',50],
    ['DF','Jack Hendry',1995,'Al-Ettifaq',37],
    ['DF','Nathan Patterson',2001,'Everton FC',26],
    ['DF','Anthony Ralston',1998,'Celtic FC',26],
    ['DF','John Souttar',1996,'Rangers FC',23],
    ['DF','Aaron Hickey',2002,'Brentford FC',20],
    ['DF','Dominic Hyam',1995,'Wrexham',3],
    ['MF','John McGinn',1994,'Aston Villa FC',85],
    ['MF','Scott McTominay',1996,'SSC Napoli',69],
    ['MF','Ryan Christie',1995,'AFC Bournemouth',67],
    ['MF','Kenny McLean',1992,'Norwich City FC',57],
    ['MF','Lewis Ferguson',1999,'Bologna FC',23],
    ['MF','Ben Doak',2005,'AFC Bournemouth',13],
    ['MF','Findlay Curtis',2006,'Kilmarnock FC',2],
    ['MF','Tyler Fletcher',2007,'Manchester United FC',1],
    ['FW','Lyndon Dykes',1995,'Charlton Athletic',51],
    ['FW','Ché Adams',1996,'Torino FC',46],
    ['FW','Lawrence Shankland',1995,'Heart of Midlothian',19],
    ['FW','George Hirst',1999,'Ipswich Town',9],
    ['FW','Ross Stewart',1996,'Southampton FC',2],
],

'USA': [
    ['GK','Matt Turner',1994,'New England Revolution',54],
    ['DF','Sergiño Dest',2000,'PSV Eindhoven',38],
    ['DF','Chris Richards',2000,'Crystal Palace FC',36],
    ['MF','Tyler Adams',1999,'AFC Bournemouth',53],
    ['DF','Antonee Robinson',1997,'Fulham FC',53],
    ['DF','Auston Trusty',1998,'Celtic FC',7],
    ['MF','Giovanni Reyna',2002,'Borussia Mönchengladbach',37],
    ['MF','Weston McKennie',1998,'Juventus FC',65],
    ['FW','Ricardo Pepi',2003,'PSV Eindhoven',36],
    ['FW','Christian Pulisic',1998,'AC Milan',85],
    ['FW','Brenden Aaronson',2000,'Leeds United',57],
    ['DF','Miles Robinson',1997,'FC Cincinnati',39],
    ['DF','Tim Ream',1987,'Charlotte FC',81],
    ['MF','Sebastian Berhalter',2001,'Vancouver Whitecaps FC',12],
    ['MF','Cristian Roldan',1995,'Seattle Sounders FC',46],
    ['DF','Alex Freeman',2004,'Villarreal CF',16],
    ['MF','Malik Tillman',2002,'Bayer 04 Leverkusen',29],
    ['DF','Maximilian Arfsten',2001,'Columbus Crew',19],
    ['FW','Haji Wright',1998,'Coventry City',20],
    ['FW','Folarin Balogun',2001,'AS Monaco',26],
    ['FW','Timothy Weah',2000,'Olympique Marseille',50],
    ['DF','Mark McKenzie',1999,'Toulouse FC',28],
    ['DF','Joe Scally',2002,'Borussia Mönchengladbach',25],
    ['GK','Matt Freese',1998,'New York City FC',14],
    ['GK','Chris Brady',2004,'Chicago Fire FC',1],
    ['FW','Alejandro Zendejas',1998,'América',14],
],

'Paraguay': [
    ['GK','Gatito Fernández',1988,'Cerro Porteño',30],
    ['GK','Orlando Gill',2000,'San Lorenzo',5],
    ['GK','Gastón Olveira',1993,'Olimpia',1],
    ['DF','Gustavo Gómez',1993,'SE Palmeiras',88],
    ['DF','Júnior Alonso',1993,'Atlético Mineiro',70],
    ['DF','Fabián Balbuena',1991,'Grêmio FBPA',47],
    ['DF','Omar Alderete',1996,'Sunderland AFC',35],
    ['DF','Juan José Cáceres',2000,'Dynamo Moscow',16],
    ['DF','Gustavo Velázquez',1991,'Cerro Porteño',12],
    ['DF','José Canale',1996,'Lanús',1],
    ['DF','Alexandro Maidana',2005,'Talleres',1],
    ['MF','Miguel Almirón',1994,'Atlanta United FC',75],
    ['MF','Kaku',1995,'Al-Ain',32],
    ['MF','Andrés Cubas',1996,'Vancouver Whitecaps FC',32],
    ['MF','Ramón Sosa',1999,'SE Palmeiras',28],
    ['MF','Diego Gómez',2003,'Brighton & Hove Albion FC',23],
    ['MF','Damián Bobadilla',2001,'São Paulo FC',19],
    ['MF','Braian Ojeda',2000,'Orlando City SC',16],
    ['MF','Matías Galarza',2002,'Atlanta United FC',14],
    ['MF','Maurício',2001,'SE Palmeiras',2],
    ['FW','Antonio Sanabria',1996,'Cremonese',47],
    ['FW','Julio Enciso',2004,'RC Strasbourg',31],
    ['FW','Gabriel Ávalos',1991,'Club Atlético Independiente',22],
    ['FW','Álex Arce',1995,'Independiente Rivadavia',14],
    ['FW','Isidro Pitta',1999,'Red Bull Bragantino',5],
    ['FW','Gustavo Caballero',2001,'Portsmouth FC',2],
],

'Türkei': [
    ['GK','Uğurcan Çakır',1996,'Galatasaray SK',38],
    ['GK','Mert Günok',1989,'Fenerbahçe SK',37],
    ['GK','Altay Bayındır',1998,'Manchester United FC',11],
    ['DF','Merih Demiral',1998,'Al-Ahli',61],
    ['DF','Zeki Çelik',1997,'AS Roma',59],
    ['DF','Çağlar Söyüncü',1996,'Fenerbahçe SK',59],
    ['DF','Mert Müldür',1999,'Fenerbahçe SK',43],
    ['DF','Ferdi Kadıoğlu',1999,'Brighton & Hove Albion FC',30],
    ['DF','Ozan Kabak',2000,'TSG Hoffenheim',28],
    ['DF','Abdülkerim Bardakcı',1994,'Galatasaray SK',26],
    ['DF','Eren Elmalı',2000,'Galatasaray SK',21],
    ['MF','Hakan Çalhanoğlu',1994,'FC Internazionale Milano',104],
    ['MF','Kaan Ayhan',1994,'Galatasaray SK',72],
    ['MF','Orkun Kökçü',2000,'Beşiktaş JK',48],
    ['MF','İsmail Yüksek',1999,'Fenerbahçe SK',31],
    ['MF','Salih Özcan',1998,'Borussia Dortmund',28],
    ['MF','Atakan Karazor',1996,'VfB Stuttgart',2],
    ['FW','Kerem Aktürkoğlu',1998,'Fenerbahçe SK',51],
    ['FW','İrfan Can Kahveci',1995,'Kasımpaşa',45],
    ['FW','Barış Alper Yılmaz',2000,'Galatasaray SK',33],
    ['FW','Arda Güler',2005,'Real Madrid C.F.',28],
    ['FW','Kenan Yıldız',2005,'Juventus FC',28],
    ['FW','Yunus Akgün',2000,'Galatasaray SK',17],
    ['FW','Oğuz Aydın',2000,'Fenerbahçe SK',9],
    ['FW','Deniz Gül',2004,'FC Porto',6],
    ['FW','Can Uzun',2005,'Eintracht Frankfurt',4],
],

'Niederlande': [
    ['GK','Bart Verbruggen',2002,'Brighton & Hove Albion FC',27],
    ['GK','Mark Flekken',1993,'Bayer 04 Leverkusen',11],
    ['GK','Robin Roefs',2003,'Sunderland AFC',0],
    ['DF','Virgil van Dijk',1991,'Liverpool FC',90],
    ['DF','Denzel Dumfries',1996,'FC Internazionale Milano',71],
    ['DF','Nathan Aké',1995,'Manchester City FC',58],
    ['DF','Jurriën Timber',2001,'Arsenal FC',23],
    ['DF','Micky van de Ven',2001,'Tottenham Hotspur FC',19],
    ['DF','Mats Wieffer',1999,'Brighton & Hove Albion FC',14],
    ['DF','Jan Paul van Hecke',2000,'Brighton & Hove Albion FC',10],
    ['DF','Jorrel Hato',2006,'Chelsea FC',7],
    ['MF','Frenkie de Jong',1997,'FC Barcelona',64],
    ['MF','Marten de Roon',1991,'Atalanta Bergamo',42],
    ['MF','Tijjani Reijnders',1998,'Manchester City FC',30],
    ['MF','Teun Koopmeiners',1998,'Juventus FC',27],
    ['MF','Ryan Gravenberch',2002,'Liverpool FC',25],
    ['MF','Justin Kluivert',1999,'AFC Bournemouth',11],
    ['MF','Quinten Timber',2001,'Olympique Marseille',10],
    ['MF','Guus Til',1997,'PSV Eindhoven',6],
    ['FW','Memphis Depay',1994,'SC Corinthians Paulista',108],
    ['FW','Wout Weghorst',1992,'AFC Ajax',51],
    ['FW','Donyell Malen',1999,'AS Roma',51],
    ['FW','Cody Gakpo',1999,'Liverpool FC',48],
    ['FW','Noa Lang',1999,'Galatasaray SK',15],
    ['FW','Brian Brobbey',2002,'Sunderland AFC',10],
    ['FW','Crysencio Summerville',2001,'West Ham United FC',0],
],

'Japan': [
    ['GK','Zion Suzuki',2002,'Parma',24],
    ['DF','Yukinari Sugawara',2000,'SV Werder Bremen',21],
    ['DF','Shōgo Taniguchi',1991,'Sint-Truiden VV',38],
    ['DF','Kō Itakura',1997,'AFC Ajax',40],
    ['DF','Yūto Nagatomo',1986,'FC Tokyo',145],
    ['MF','Wataru Endo',1993,'Liverpool FC',73],
    ['MF','Ao Tanaka',1998,'Leeds United',38],
    ['MF','Takefusa Kubo',2001,'Real Sociedad',49],
    ['FW','Keisuke Gotō',2005,'Sint-Truiden VV',4],
    ['MF','Ritsu Dōan',1998,'Eintracht Frankfurt',65],
    ['FW','Daizen Maeda',1997,'Celtic FC',27],
    ['GK','Keisuke Ōsako',1999,'Sanfrecce Hiroshima',11],
    ['MF','Keito Nakamura',2000,'Stade de Reims',25],
    ['MF','Junya Itō',1993,'KRC Genk',69],
    ['MF','Daichi Kamada',1996,'Crystal Palace FC',49],
    ['DF','Tsuyoshi Watanabe',1997,'Feyenoord Rotterdam',11],
    ['FW','Yuito Suzuki',2001,'SC Freiburg',6],
    ['FW','Ayase Ueda',1998,'Feyenoord Rotterdam',39],
    ['FW','Kōki Ogawa',1997,'NEC Nijmegen',15],
    ['DF','Ayumu Seko',2000,'Le Havre AC',14],
    ['DF','Hiroki Itō',1999,'FC Bayern München',24],
    ['DF','Takehiro Tomiyasu',1998,'AFC Ajax',43],
    ['GK','Tomoki Hayakawa',1999,'Kashima Antlers',4],
    ['MF','Kaishū Sano',2000,'1. FSV Mainz 05',13],
    ['DF','Junnosuke Suzuki',2003,'FC København',6],
    ['FW','Kento Shiogai',2005,'VfL Wolfsburg',2],
],

'Schweden': [
    ['GK','Jacob Widell Zetterström',1998,'Derby County',3],
    ['DF','Gustaf Lagerbielke',2000,'SC Braga',10],
    ['DF','Victor Lindelöf',1994,'Aston Villa FC',76],
    ['DF','Isak Hien',1999,'Atalanta Bergamo',28],
    ['DF','Gabriel Gudmundsson',1999,'Leeds United',23],
    ['DF','Herman Johansson',1997,'FC Dallas',3],
    ['MF','Lucas Bergvall',2006,'Tottenham Hotspur FC',9],
    ['DF','Daniel Svensson',2002,'Borussia Dortmund',12],
    ['FW','Alexander Isak',1999,'Liverpool FC',57],
    ['FW','Benjamin Nygren',2001,'Celtic FC',10],
    ['FW','Anthony Elanga',2002,'Newcastle United FC',29],
    ['GK','Viktor Johansson',1998,'Stoke City',12],
    ['FW','Ken Sema',1993,'Pafos FC',33],
    ['DF','Hjalmar Ekdal',1998,'Burnley',12],
    ['DF','Carl Starfelt',1995,'RC Celta de Vigo',17],
    ['MF','Jesper Karlström',1995,'Udinese Calcio',24],
    ['FW','Viktor Gyökeres',1998,'Arsenal FC',32],
    ['MF','Yasin Ayari',2003,'Brighton & Hove Albion FC',20],
    ['MF','Mattias Svanberg',1999,'VfL Wolfsburg',40],
    ['DF','Eric Smith',1997,'FC St. Pauli',1],
    ['FW','Alexander Bernhardsson',1998,'Holstein Kiel',10],
    ['MF','Besfort Zeneli',2002,'Royale Union Saint-Gilloise',7],
    ['GK','Kristoffer Nordfeldt',1989,'AIK',20],
    ['DF','Elliot Stroud',2002,'Mjällby AIF',0],
    ['FW','Gustaf Nilsson',1997,'Club Brugge',9],
    ['FW','Taha Ali',1998,'Malmö FF',1],
],

'Tunesien': [
    ['GK','Aymen Dahmen',1997,'CS Sfaxien',37],
    ['GK','Sabri Ben Hessen',1996,'Étoile du Sahel',2],
    ['GK','Mouhib Chamakh',2001,'Club Africain',1],
    ['DF','Montassar Talbi',1998,'Lorient',62],
    ['DF','Dylan Bronn',1995,'Servette FC',52],
    ['DF','Ali Abdi',1993,'OGC Nice',45],
    ['DF','Yan Valery',1999,'BSC Young Boys',21],
    ['DF','Mohamed Amine Ben Hamida',1995,'Espérance de Tunis',12],
    ['DF','Moutaz Neffati',2004,'IFK Norrköping',5],
    ['DF','Omar Rekik',2001,'NK Maribor',4],
    ['DF','Adem Arous',2004,'Kasımpaşa',1],
    ['DF','Raed Chikhaoui',2004,'US Monastir',0],
    ['MF','Ellyes Skhiri',1995,'Eintracht Frankfurt',81],
    ['MF','Hannibal Mejbri',2003,'Burnley',44],
    ['MF','Anis Ben Slimane',2001,'Norwich City FC',39],
    ['MF','Mortadha Ben Ouanes',1994,'Kasımpaşa',17],
    ['MF','Ismaël Gharbi',2004,'FC Augsburg',15],
    ['MF','Hadj Mahmoud',2000,'FC Lugano',7],
    ['MF','Rani Khedira',1994,'1. FC Union Berlin',2],
    ['FW','Elias Achouri',1999,'FC København',29],
    ['FW','Firas Chaouat',1996,'Club Africain',28],
    ['FW','Hazem Mastouri',1997,'Dynamo Makhachkala',18],
    ['FW','Elias Saad',1999,'Hannover 96',14],
    ['FW','Sebastian Tounekti',2002,'Celtic FC',10],
    ['FW','Khalil Ayari',2005,'Paris Saint-Germain',2],
    ['FW','Rayan Elloumi',2007,'Vancouver Whitecaps FC',2],
],

# ── Trainingsdata (ca.) ───────────────────────────────────────────────────────

'Spanien': [
    ['GK','Unai Simón',1997,'Athletic Club',42],
    ['GK','David Raya',1995,'Arsenal FC',18],
    ['GK','Álex Remiro',1995,'Real Sociedad',12],
    ['DF','Dani Carvajal',1992,'Real Madrid C.F.',82],
    ['DF','Alejandro Balde',2003,'FC Barcelona',22],
    ['DF','Pau Cubarsí',2007,'FC Barcelona',12],
    ['DF','Robin Le Normand',2000,'Atlético de Madrid',26],
    ['DF','Nacho Fernández',1990,'Al-Qadsiah',45],
    ['DF','Dani Vivian',1999,'Athletic Club',18],
    ['DF','Íñigo Martínez',1991,'FC Barcelona',39],
    ['DF','Mario Hermoso',1995,'AS Roma',22],
    ['MF','Pedri',2002,'FC Barcelona',46],
    ['MF','Fabián Ruiz',1996,'Paris Saint-Germain',38],
    ['MF','Mikel Merino',1996,'Arsenal FC',38],
    ['MF','Martín Zubimendi',1999,'Liverpool FC',22],
    ['MF','Dani Olmo',1998,'FC Barcelona',42],
    ['MF','Aleix García',1997,'Manchester City FC',12],
    ['MF','Bryan Gil',2001,'Girona FC',18],
    ['MF','Marcos Llorente',1995,'Atlético de Madrid',52],
    ['FW','Álvaro Morata',1992,'AC Milan',76],
    ['FW','Ferran Torres',2000,'FC Barcelona',52],
    ['FW','Nico Williams',2002,'Athletic Club',32],
    ['FW','Lamine Yamal',2007,'FC Barcelona',28],
    ['FW','Mikel Oyarzabal',1997,'Real Sociedad',68],
    ['FW','Joselu',1990,'Al-Qadsiah',14],
    ['FW','Ansu Fati',2002,'Brighton & Hove Albion FC',24],
],

'Portugal': [
    ['GK','Diogo Costa',1999,'FC Porto',22],
    ['GK','José Sá',1993,'Wolverhampton Wanderers FC',12],
    ['GK','Rui Patrício',1988,'AS Roma',108],
    ['DF','Rúben Dias',1997,'Manchester City FC',66],
    ['DF','Nuno Mendes',2002,'Paris Saint-Germain',38],
    ['DF','Diogo Dalot',1999,'Manchester United FC',46],
    ['DF','João Cancelo',1994,'Al-Hilal',56],
    ['DF','Gonçalo Inácio',2001,'Sporting CP',24],
    ['DF','António Silva',2003,'SL Benfica',22],
    ['DF','Renato Veiga',2003,'Chelsea FC',10],
    ['DF','Danilo Pereira',1991,'Paris Saint-Germain',66],
    ['MF','Bruno Fernandes',1994,'Manchester United FC',86],
    ['MF','Vitinha',2000,'Paris Saint-Germain',38],
    ['MF','João Palhinha',1995,'FC Bayern München',48],
    ['MF','Bernardo Silva',1994,'Manchester City FC',108],
    ['MF','Rúben Neves',1997,'Al-Hilal',78],
    ['MF','Matheus Nunes',2000,'Manchester City FC',28],
    ['MF','William Carvalho',1992,'Real Betis',96],
    ['MF','João Neves',2004,'Paris Saint-Germain',18],
    ['FW','Cristiano Ronaldo',1985,'Al-Nassr',215],
    ['FW','Rafael Leão',1999,'AC Milan',48],
    ['FW','Pedro Neto',2000,'Chelsea FC',38],
    ['FW','Diogo Jota',1996,'Liverpool FC',55],
    ['FW','João Félix',1999,'FC Barcelona',52],
    ['FW','Gonçalo Ramos',2001,'Paris Saint-Germain',32],
    ['FW','Francisco Trincão',1999,'Sporting CP',22],
],

'Norwegen': [
    ['GK','Ørjan Nyland',1990,'Ipswich Town',72],
    ['GK','Kristoffer Klaesson',2000,'RB Leipzig',8],
    ['GK','Sten Michael Grytebust',1990,'Start',4],
    ['DF','Leo Østigård',1999,'SSC Napoli',38],
    ['DF','Stefan Strandberg',1994,'Ferencvárosi TC',48],
    ['DF','Andreas Hanche-Olsen',1997,'Mainz 05',22],
    ['DF','Birger Meling',1994,'Stade Rennais FC',46],
    ['DF','Kristoffer Ajer',1998,'Brentford FC',52],
    ['DF','Fredrik Bjørkan',1999,'IFK Göteborg',20],
    ['DF','Stian Gregersen',1997,'Girona FC',14],
    ['DF','Marcus Pedersen',1999,'Feyenoord Rotterdam',22],
    ['MF','Martin Ødegaard',1998,'Arsenal FC',88],
    ['MF','Sander Berge',1998,'Fulham FC',60],
    ['MF','Mathias Normann',1996,'Rapid Wien',42],
    ['MF','Fredrik Aursnes',1995,'SL Benfica',48],
    ['MF','Kristian Thorstvedt',2000,'Sassuolo',22],
    ['MF','Mats Møller Dæhli',1995,'FC St. Pauli',38],
    ['MF','Patrick Berg',1997,'Bodo/Glimt',12],
    ['FW','Erling Haaland',2000,'Manchester City FC',42],
    ['FW','Alexander Sørloth',1995,'Atlético de Madrid',58],
    ['FW','Joshua King',1992,'Besiktas JK',102],
    ['FW','Kasper Dolberg',1997,'Anderlecht',38],
    ['FW','Mohamed Elyounoussi',1994,'Celtic FC',68],
    ['FW','Ola Solbakken',1998,'AS Roma',28],
    ['FW','Jørgen Strand Larsen',1999,'RC Celta de Vigo',22],
    ['FW','Antonio Nusa',2005,'RB Leipzig',14],
],

'Uruguay': [
    ['GK','Sergio Rochet',1993,'CA River Plate',48],
    ['GK','Santiago Mele',1997,'Montevideo City Torque',12],
    ['GK','Guillermo De Amores',1994,'CD Nacional',8],
    ['DF','José María Giménez',1995,'Atlético de Madrid',82],
    ['DF','Ronald Araújo',1999,'FC Barcelona',52],
    ['DF','Mathías Olivera',1997,'SSC Napoli',46],
    ['DF','Sebastián Coates',1991,'Sporting CP',72],
    ['DF','Emiliano Velázquez',1995,'Pumas UNAM',18],
    ['DF','Joaquín Piquerez',1999,'SE Palmeiras',32],
    ['DF','Facundo González',2001,'Valencia CF',12],
    ['DF','Marcelo Saracchi',1998,'FC Lorient',8],
    ['MF','Federico Valverde',1998,'Real Madrid C.F.',72],
    ['MF','Rodrigo Bentancur',1997,'Tottenham Hotspur FC',68],
    ['MF','Manuel Ugarte',2001,'Manchester United FC',36],
    ['MF','Nicolás De La Cruz',1997,'CR Flamengo',48],
    ['MF','Giorgian De Arrascaeta',1994,'CR Flamengo',66],
    ['MF','Brian Rodríguez',1999,'Los Angeles FC',22],
    ['MF','Nahitan Nández',1996,'Cagliari Calcio',62],
    ['FW','Darwin Núñez',1999,'Liverpool FC',52],
    ['FW','Maximiliano Araújo',2000,'Sporting CP',22],
    ['FW','Facundo Pellistri',2001,'Manchester United FC',28],
    ['FW','Santiago Ramos Mingo',2005,'CA Boca Juniors',8],
    ['FW','Agustín Álvarez',2001,'SS Lazio',18],
    ['FW','Luciano Rodríguez',2003,'Liverpool FC',12],
    ['FW','Diego Rossi',1998,'Fenerbahçe SK',38],
    ['FW','Dante Elizondo',2003,'CF Pachuca',4],
],

'Iran': [
    ['GK','Alireza Beiranvand',1992,'Persepolis FC',88],
    ['GK','Hossein Hosseini',1999,'Perspolis FC',14],
    ['GK','Payam Niazmand',1994,'Tractor SC',8],
    ['DF','Shoja Khalilzadeh',1990,'Persepolis FC',74],
    ['DF','Ramin Rezaeian',1990,'Sepahan SC',78],
    ['DF','Milad Mohammadi',1993,'AEK Athens',68],
    ['DF','Majid Hosseini',1999,'Kasımpaşa',32],
    ['DF','Sadegh Moharrami',1995,'GNK Dinamo Zagreb',48],
    ['DF','Abolfazl Jalali',1997,'Esteghlal FC',18],
    ['DF','Hossein Kanaanizadegan',2001,'Persepolis FC',14],
    ['DF','Mohammad Mohebbi',1996,'Persepolis FC',12],
    ['MF','Alireza Jahanbakhsh',1994,'Feyenoord Rotterdam',98],
    ['MF','Saeid Ezatolahi',1996,'Qarabag FK',62],
    ['MF','Ahmad Nourollahi',1995,'Esteghlal FC',56],
    ['MF','Ali Karimi',2002,'Feyenoord Rotterdam',18],
    ['MF','Ehsan Hajsafi',1990,'Olympiacos FC',126],
    ['MF','Mohammad Karimi',1998,'Teheran',24],
    ['MF','Omid Ebrahimi',1987,'Sepahan SC',88],
    ['FW','Mehdi Taremi',1992,'FC Internazionale Milano',102],
    ['FW','Sardar Azmoun',1995,'Bayer 04 Leverkusen',78],
    ['FW','Karim Ansarifard',1990,'Atromitos FC',102],
    ['FW','Allahyar Sayyadmanesh',2001,'Lecce',22],
    ['FW','Saman Ghoddos',1994,'Brentford FC',52],
    ['FW','Vahid Amiri',1990,'Persepolis FC',88],
    ['FW','Ali Gholizadeh',1997,'Charlotte FC',32],
    ['FW','Ahmad Abedzadeh',2002,'Angers SCO',8],
],

'Irak': [
    ['GK','Jalal Hassan',1989,'Zamalek SC',72],
    ['GK','Mohammed Hameed',1997,'Al-Zawraa',18],
    ['GK','Ali Bassem',2002,'Al-Shorta',4],
    ['DF','Ali Adnan',1994,'Colorado Rapids',88],
    ['DF','Rebin Sulaka',1997,'FC Emmen',22],
    ['DF','Saad Natiq',1993,'Al-Zawraa',48],
    ['DF','Ahmed Salam',1995,'Al-Shorta',38],
    ['DF','Yaser Kasim',1991,'Brisbane Roar',54],
    ['DF','Alaa Abbas',1998,'Al-Zawraa',28],
    ['DF','Mohammed Al-Hamdani',2001,'1. FC Union Berlin',8],
    ['MF','Amjad Attwan',1990,'Al-Zawraa',62],
    ['MF','Balal Faiq',1994,'FC Augsburg',48],
    ['MF','Ayman Hussein',1993,'Al-Zawraa',78],
    ['MF','Safaa Hadi',1994,'Al-Zawraa',52],
    ['MF','Karrar Mohammad',2001,'Feyenoord Rotterdam',14],
    ['MF','Hussein Ali',1997,'Al-Qasimy',32],
    ['MF','Hussain Bakarman',1994,'Al-Riffa',28],
    ['FW','Aymen Hussein',1993,'Al-Zawraa',78],
    ['FW','Mohanad Ali',1993,'Apollon Limassol',62],
    ['FW','Hammadi Ahmed',1989,'Al-Zawraa',92],
    ['FW','Mahdi Kamil',1996,'Sepahan SC',38],
    ['FW','Ahmed Yasin',1991,'AEL Limassol',48],
    ['FW','Dana Hawel',1991,'Esteghlal Tehran FC',66],
    ['FW','Ameen Al-Dakhil',2003,'Standard Liège',12],
    ['GK','Ahmed Basil',1999,'Al-Zawraa',8],
    ['DF','Ali Jasim',2003,'AFC Ajax',6],
],

'Jordanien': [
    ['GK','Yazeed Abo Laila',1993,'Al-Faisaly',52],
    ['GK','Ahmad Rashed',1997,'Al-Jazeera',18],
    ['GK','Amer Shafi',1989,'Shabab Al-Ahli',44],
    ['DF','Baha\' Abdelrahman',1993,'Al-Wehdat',62],
    ['DF','Mutaz Yaseen',1992,'Al-Ramtha',48],
    ['DF','Khaled Qutishat',1990,'Al-Faisaly',38],
    ['DF','Mohammad Hdeib',1998,'Górnik Zabrze',22],
    ['DF','Ehsan Haddad',1990,'Al-Faisaly',46],
    ['DF','Abdullah Nasib',1997,'Hapoel Haifa',18],
    ['DF','Basel Dawdouh',1994,'Al-Sareeh',28],
    ['MF','Yazan Al-Naimat',1998,'Al-Wehdat',32],
    ['MF','Musa Al-Tamari',1997,'Montpellier HSC',42],
    ['MF','Nizar Al-Momani',1994,'Al-Faisaly',52],
    ['MF','Ahmad Hayel',1993,'Al-Wehdat',38],
    ['MF','Abdallah Nasib',2000,'Al-Faisaly',14],
    ['MF','Obada Al-Rashdan',1995,'Al-Faisaly',36],
    ['MF','Emad Al-Lahham',1993,'Al-Wahda',28],
    ['FW','Yazan Al-Arab',1997,'Shabab Al-Ahli',48],
    ['FW','Khalil Bani Attia',1994,'Al-Shorta',38],
    ['FW','Mohammad Al-Nabulsi',1999,'Djurgårdens IF',22],
    ['FW','Ahmad Zyoud',1993,'Al-Ramtha',32],
    ['FW','Feras Ibrahim',1994,'Anorthosis Famagusta',26],
    ['FW','Musa Natiq',2001,'Al-Faisaly',8],
    ['DF','Zaid Qunbar',2002,'Al-Jazeera',6],
    ['MF','Hamza Al-Dardour',1990,'Al-Wehdat',66],
    ['FW','Salam Radi',1994,'Al-Faisaly',38],
],

'Neuseeland': [
    ['GK','Oliver Sail',1999,'FC Nordsjælland',22],
    ['GK','Stefan Marinovic',1991,'Vancouver Whitecaps FC',38],
    ['GK','Michael Woud',1998,'Ferencvárosi TC',14],
    ['DF','Nando Pijnaker',1999,'Deportivo Alavés',28],
    ['DF','Liberato Cacace',2000,'Empoli FC',36],
    ['DF','Tim Payne',1995,'Los Angeles FC',22],
    ['DF','Michael Boxall',1988,'Minnesota United FC',52],
    ['DF','Alex Greive',2000,'Go Ahead Eagles',14],
    ['DF','Callum McCowatt',1998,'Go Ahead Eagles',16],
    ['DF','Dane Ingham',1995,'AIK',22],
    ['DF','Cameron Howieson',1996,'Livingston FC',12],
    ['MF','Joe Bell',1999,'Middlesbrough FC',32],
    ['MF','Clayton Lewis',1997,'Stade Rennais FC',28],
    ['MF','Marco Rojas',1992,'FC Zurich',48],
    ['MF','Ben Old',2001,'Sporting CP',12],
    ['MF','Marko Stamenic',2001,'FC Copenhagen',18],
    ['MF','Riley Bidois',2002,'Roda JC Kerkrade',8],
    ['MF','Elijah Just',2002,'Auckland FC',6],
    ['FW','Chris Wood',1991,'Nottingham Forest FC',122],
    ['FW','Sarpreet Singh',1999,'Jahn Regensburg',38],
    ['FW','Myer Bevan',1998,'FC Emmen',22],
    ['FW','Matthew Garbett',1999,'FC Emmen',14],
    ['FW','Hamish Watson',2002,'Ferencvárosi TC',8],
    ['FW','Callan Elliot',2003,'Stade Rennais FC',12],
    ['GK','Jacob Spoonley',2001,'Meippen',4],
    ['DF','Jonah Hintz',2001,'Bodo/Glimt',6],
],

'Panama': [
    ['GK','Luis Mejía',1991,'Frosinone',36],
    ['GK','Orlando Mosquera',1993,'Deportivo Independiente',18],
    ['GK','Alex Rodríguez',2000,'CD Victoria',6],
    ['DF','Fidel Escobar',1996,'New York Red Bulls',56],
    ['DF','Harold Cummings',1992,'Santos Laguna',46],
    ['DF','Eric Davis',1993,'Almería',58],
    ['DF','Azmahar Ariano',1998,'Sporting Kansas City',22],
    ['DF','César Yanis',1993,'CF Pachuca',38],
    ['DF','Édgar Bárcenas',1994,'Vitesse',28],
    ['DF','Nicolás Caisedo',2002,'CD Saprissa',8],
    ['DF','Andrés Andrade',1994,'Deportivo Saprissa',32],
    ['MF','Adalberto Carrasquilla',1997,'KV Kortrijk',48],
    ['MF','Abdiel Ayarza',1999,'CD Guadalajara',28],
    ['MF','Cristian Martínez',1996,'Real Oviedo',38],
    ['MF','Aníbal Godoy',1990,'Nashville SC',88],
    ['MF','Carlos Harvey',2001,'Columbus Crew',12],
    ['MF','Alberto Quintero',1989,'CD Olimpia',62],
    ['MF','Ronaldo Walker',2002,'Nashville SC',8],
    ['FW','Ismael Díaz',2000,'Villarreal CF',28],
    ['FW','José Fajardo',1994,'Millwall',48],
    ['FW','Gabriel Torres',1988,'Arabe Unido',62],
    ['FW','Freddy Góndola',1991,'CF Pachuca',28],
    ['FW','Jesús Médico',1999,'CD Plaza Amador',12],
    ['FW','Cecilio Waterman',1993,'CF Montréal',58],
    ['GK','Luis Penedo',1988,'Independiente',36],
    ['DF','Andrés Andrade',1994,'Deportivo Saprissa',32],
],

'Saudi-Arabien': [
    ['GK','Mohammed Al-Owais',1991,'Al-Hilal',68],
    ['GK','Mohammed Al-Rubaie',1999,'Al-Fayha',14],
    ['GK','Nawaf Al-Aqidi',1997,'Al-Nassr',8],
    ['DF','Ali Al-Bulaihi',1989,'Al-Hilal',82],
    ['DF','Hassan Tambakti',1999,'Al-Hilal',28],
    ['DF','Saud Abdulhamid',1999,'AS Roma',38],
    ['DF','Mohammed Al-Burayk',1994,'Al-Hilal',66],
    ['DF','Sultan Al-Ghannam',1997,'Al-Nassr',32],
    ['DF','Abdulelah Al-Amri',1997,'Al-Fateh',22],
    ['DF','Tariq Salman',1996,'Al-Qadsiah',18],
    ['DF','Abdullah Madu',2000,'Al-Shabab',12],
    ['MF','Riyadh Sharahili',1993,'Al-Hilal',68],
    ['MF','Sami Al-Najei',1996,'Al-Nassr',42],
    ['MF','Haitham Asiri',1996,'Al-Ettifaq',38],
    ['MF','Abdulellah Al-Malki',1997,'Al-Hilal',52],
    ['MF','Salman Al-Faraj',1989,'Al-Hilal',102],
    ['MF','Mohamed Kanno',1998,'Al-Hilal',48],
    ['MF','Nasser Al-Dawsari',1991,'Al-Hilal',78],
    ['FW','Salem Al-Dawsari',1991,'Al-Hilal',88],
    ['FW','Firas Al-Buraikan',1999,'Al-Fateh',42],
    ['FW','Saleh Al-Shehri',1993,'Al-Hilal',56],
    ['FW','Ali Al-Hassan',2002,'Al-Hilal',22],
    ['FW','Fahad Al-Muwallad',1994,'Al-Ittihad',72],
    ['FW','Hattan Bahebri',1996,'Al-Shabab',38],
    ['FW','Seba Al-Ruwaili',2001,'Al-Nassr',14],
    ['MF','Abdullah Al-Hamdan',2000,'Al-Shabab',28],
],

'Senegal': [
    ['GK','Édouard Mendy',1992,'Al-Ahli',68],
    ['GK','Alfred Gomis',1993,'Rennes',32],
    ['GK','Seny Dieng',1994,'Middlesbrough FC',22],
    ['DF','Kalidou Koulibaly',1991,'Al-Hilal',102],
    ['DF','Abdou Diallo',1996,'RB Leipzig',52],
    ['DF','Youssouf Sabaly',1993,'Real Betis',46],
    ['DF','Formose Mendy',1998,'Nantes',28],
    ['DF','Ismail Jakobs',1999,'AS Monaco',18],
    ['DF','Pape Abou Cissé',1995,'Olympiacos FC',28],
    ['DF','Moussa Niakhate',1996,'Nottingham Forest FC',18],
    ['DF','Faly Mandiang',2001,'TSG Hoffenheim',8],
    ['MF','Idrissa Gueye',1989,'Everton FC',122],
    ['MF','Nampalys Mendy',1992,'Leicester City FC',52],
    ['MF','Pape Matar Sarr',2002,'Tottenham Hotspur FC',28],
    ['MF','Lamine Camara',2003,'AS Monaco',18],
    ['MF','Krepin Diatta',1999,'AS Monaco',38],
    ['MF','Mamadou Loum',1996,'Rayo Vallecano',28],
    ['MF','Pathé Ciss',1994,'Rayo Vallecano',22],
    ['FW','Sadio Mané',1992,'Al-Nassr',114],
    ['FW','Ismaïla Sarr',1998,'Crystal Palace FC',62],
    ['FW','Nicolas Jackson',2001,'Chelsea FC',28],
    ['FW','Boulaye Dia',1996,'SS Lazio',38],
    ['FW','Habib Diallo',1994,'Strasbourg',48],
    ['FW','Iliman Ndiaye',2000,'Everton FC',22],
    ['FW','Cherif Ndiaye',2000,'KV Oostende',12],
    ['FW','Abdallah Sima',2001,'Brighton & Hove Albion FC',18],
],

'Usbekistan': [
    ['GK','Ignatiy Nesterov',1995,'Pakhtakor',38],
    ['GK','Utkir Yusupov',1993,'Navbahor',22],
    ['GK','Hamza Karimov',2000,'Pakhtakor',8],
    ['DF','Akbar Mirzoyev',1995,'Pakhtakor',48],
    ['DF','Dostonbek Khamdamov',1997,'Nasaf',36],
    ['DF','Umid Baynazarov',1999,'Pakhtakor',28],
    ['DF','Jamshid Iskandarov',1998,'Pakhtakor',22],
    ['DF','Manuchehr Jalolov',2001,'FK Metallurg',14],
    ['DF','Shamsiddin Shoev',1997,'Pakhtakor',18],
    ['DF','Rustam Ashurmatov',1998,'Buriram United',22],
    ['DF','Timur Suyunov',2002,'Pakhtakor',8],
    ['MF','Otabek Shukurov',1993,'Pakhtakor',62],
    ['MF','Jaloliddin Masharipov',1993,'Pakhtakor',72],
    ['MF','Bobur Abdixoliqov',1996,'Pakhtakor',48],
    ['MF','Dilshod Nematov',1992,'Pakhtakor',52],
    ['MF','Jamshid Sultanov',2000,'Pakhtakor',22],
    ['MF','Husan Abdullaev',1999,'FK AGMK',28],
    ['MF','Abbosbek Fayzullayev',2000,'Red Bull Salzburg',32],
    ['FW','Eldor Shomurodov',1995,'AS Roma',62],
    ['FW','Oybek Dzaksybekov',1994,'Pakhtakor',38],
    ['FW','Khojimat Erkinov',2001,'Pakhtakor',22],
    ['FW','Aziz Pardayev',1993,'Pakhtakor',28],
    ['FW','Asilbek Ismatov',2002,'FK AGMK',14],
    ['FW','Otabek Ostonov',2001,'Lokomotiv Tashkent',12],
    ['GK','Oybek Teshaev',2001,'Nasaf',4],
    ['MF','Qodir Hamrobekov',2003,'Pakhtakor',6],
],

}

# ── CSV-Export ────────────────────────────────────────────────────────────────

# 1) teams.csv
team_rows = []
for gruppe, teams in GRUPPEN:
    for team in teams:
        team_rows.append({'Gruppe': gruppe, 'Mannschaft': team})

teams_path = os.path.join(OUT, 'wm2026_teams.csv')
with open(teams_path, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=['Gruppe', 'Mannschaft'])
    w.writeheader()
    w.writerows(team_rows)
print(f'✓ {teams_path}  ({len(team_rows)} Teams)')

# 2) kader.csv
kader_rows = []
for nation, spieler in sorted(KADER.items()):
    for p in spieler:
        kader_rows.append({
            'Nation': nation,
            'Position': p[0],
            'Name': p[1],
            'Jahrgang': p[2],
            'Verein': p[3],
            'Länderspiele': p[4],
        })

kader_path = os.path.join(OUT, 'wm2026_kader.csv')
with open(kader_path, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=['Nation','Position','Name','Jahrgang','Verein','Länderspiele'])
    w.writeheader()
    w.writerows(kader_rows)
print(f'✓ {kader_path}  ({len(kader_rows)} Spieler in {len(KADER)} Mannschaften)')

# Fehlende Mannschaften?
all_teams = {t for _, ts in GRUPPEN for t in ts}
missing = all_teams - set(KADER.keys())
if missing:
    print(f'⚠ Kein Kader für: {", ".join(sorted(missing))}')
else:
    print('✓ Alle 48 Mannschaften enthalten')

# ── WM_KADER_DATA in WM_Rangverlauf.html injizieren ─────────────────────────
html_path = os.path.join(OUT, 'WM_Rangverlauf.html')
if not os.path.exists(html_path):
    print(f'⚠ {html_path} nicht gefunden – HTML nicht aktualisiert')
else:
    # Daten als JS-Objekt bauen
    js_data = {}
    for nation, spieler in KADER.items():
        js_data[nation] = [
            {'pos': p[0], 'name': p[1], 'jg': p[2], 'club': p[3], 'caps': p[4], 'land': CLUB_LAND.get(p[3], '')}
            for p in spieler
        ]
    js_var = 'var WM_KADER_DATA = ' + json.dumps(js_data, ensure_ascii=False, indent=None) + ';'

    with open(html_path, encoding='utf-8') as f:
        html = f.read()

    html_new = re.sub(
        r'/\* WM_KADER_DATA_START \*/.*?/\* WM_KADER_DATA_END \*/',
        f'/* WM_KADER_DATA_START */\n{js_var}\n/* WM_KADER_DATA_END */',
        html, flags=re.DOTALL
    )

    if html_new == html:
        print('⚠ Marker /* WM_KADER_DATA_START/END */ nicht gefunden – HTML unverändert')
    else:
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_new)
        print(f'✓ {html_path} mit Kaderdaten aktualisiert')
